"""Production persistence for pitch_type_pre (Phase 2a, decision [183]).

Writes the canonical files the registry + ONNX export consume, into
``artifacts/pitch_type_pre/<version>/``:

    model.lgb              LightGBM y7 booster
    calibrator.json        the single-scalar temperature calibrator
    feature_pipeline.json  copied from /contracts/feature_pipeline_pitchtype.json
    park_id_mapping.json   the loader's deterministic park_id -> int
    metadata.json          provenance (git sha, data hash, window, hyperparams, CV summary)
    training_data.parquet  the test-fold snapshot (ONNX-export parity + downstream eval)
    eval/                  generated by bullpen_training.eval.artifact

Deliberately simpler than pitch.persist: pitch-type has NO target-encoding lookups
(no pitcher_te/batter_te) and calibrates with temperature (not per-class isotonic), so
the on-disk set is model.lgb + calibrator.json + the contract copy + park_id_mapping +
metadata + parquet + eval/.
"""

from __future__ import annotations

import hashlib
import json
import logging
import shutil
import subprocess
from dataclasses import dataclass
from datetime import UTC, datetime
from pathlib import Path
from typing import Any

import numpy as np
import pandas as pd

from bullpen_training.eval.artifact import (
    ArtifactInputs,
    hash_dataframe,
    lightgbm_feature_importance,
)
from bullpen_training.eval.artifact import (
    generate as generate_eval,
)
from bullpen_training.eval.cv_harness import CVResult
from bullpen_training.pitch_type import PITCH_TYPE_CLASSES
from bullpen_training.pitch_type.train import ModelBundle

log = logging.getLogger(__name__)

REPO_ROOT = Path(__file__).resolve().parents[4]
DEFAULT_ARTIFACTS_DIR = REPO_ROOT / "training" / "artifacts"
CONTRACT_PATH = REPO_ROOT / "contracts" / "feature_pipeline_pitchtype.json"
MODEL_NAME = "pitch_type_pre"

# Segment the held-out eval by the loader's encoded column names (analogous to the
# pitch-outcome defaults); segment_metrics silently skips any that are absent.
_SEGMENT_COLS = ("throws_i", "stand_i", "park_i", "balls", "strikes", "inning")


@dataclass(frozen=True)
class PitchTypePersistInputs:
    model_version: str
    train_window: str
    val_window: str
    test_df: pd.DataFrame
    test_predictions: np.ndarray
    cv_result: CVResult
    hyperparams: dict[str, Any]
    park_id_mapping: dict[str, int] | None = None


def _git_commit_sha() -> str:
    try:
        return subprocess.check_output(
            ["git", "rev-parse", "HEAD"], cwd=str(REPO_ROOT), text=True
        ).strip()
    except (subprocess.CalledProcessError, FileNotFoundError):
        return "unknown"


def _sha256_of_path(path: Path) -> str:
    h = hashlib.sha256()
    with path.open("rb") as fh:
        for chunk in iter(lambda: fh.read(8192), b""):
            h.update(chunk)
    return h.hexdigest()


def _write_park_id_mapping(out_dir: Path, mapping: dict[str, int]) -> Path:
    """park_id -> int, sorted by key for byte-stability (mirrors pitch.persist's shape)."""
    payload = {"park_id": dict(sorted(mapping.items())), "missing_value": -1}
    path = out_dir / "park_id_mapping.json"
    path.write_text(json.dumps(payload, indent=2, sort_keys=False) + "\n")
    return path


def _write_metadata(
    out_dir: Path,
    inputs: PitchTypePersistInputs,
    model_path: Path,
    *,
    training_data_hash: str,
    calibrator_path: Path,
) -> Path:
    payload: dict[str, Any] = {
        "model_name": MODEL_NAME,
        "model_version": inputs.model_version,
        "phase": "2a",
        "training_data_window": inputs.train_window,
        "val_window": inputs.val_window,
        "training_data_hash": training_data_hash,
        "model_artifact": {"path": model_path.name, "sha256": _sha256_of_path(model_path)},
        "calibrator": {
            "path": calibrator_path.name,
            "sha256": _sha256_of_path(calibrator_path),
            "kind": "temperature",
        },
        "feature_pipeline_hash": json.loads(CONTRACT_PATH.read_text())["schema_hash"],
        "git_commit": _git_commit_sha(),
        "trained_at": datetime.now(UTC).isoformat(timespec="seconds"),
        "hyperparams": inputs.hyperparams,
        "eval_metrics_summary": {
            name: {"mean": mean, "std": std}
            for name, (mean, std) in inputs.cv_result.summary.items()
        },
        "eval_metrics_per_fold": [
            {
                "fold_id": fr.fold_id,
                "train_rows": fr.train_rows,
                "val_rows": fr.val_rows,
                "test_rows": fr.test_rows,
                "metrics": fr.metrics,
            }
            for fr in inputs.cv_result.per_fold
        ],
    }
    meta_path = out_dir / "metadata.json"
    meta_path.write_text(json.dumps(payload, indent=2, sort_keys=False) + "\n")
    return meta_path


def persist_pitch_type_v1(
    bundle: ModelBundle,
    inputs: PitchTypePersistInputs,
    *,
    artifacts_dir: Path | None = None,
) -> Path:
    """Write the canonical files + eval/ for the pitch-type LightGBM bundle."""
    base = artifacts_dir or DEFAULT_ARTIFACTS_DIR
    out_dir = base / MODEL_NAME / inputs.model_version
    out_dir.mkdir(parents=True, exist_ok=True)

    model_path = out_dir / "model.lgb"
    bundle.booster.save_model(str(model_path))

    cal_path = out_dir / "calibrator.json"
    bundle.calibrator.to_json(cal_path)

    shutil.copyfile(CONTRACT_PATH, out_dir / "feature_pipeline.json")
    if inputs.park_id_mapping is not None:
        _write_park_id_mapping(out_dir, inputs.park_id_mapping)

    snapshot_path = out_dir / "training_data.parquet"
    inputs.test_df.to_parquet(snapshot_path, index=False)
    data_hash = hash_dataframe(inputs.test_df)

    _write_metadata(
        out_dir, inputs, model_path, training_data_hash=data_hash, calibrator_path=cal_path
    )

    fi = lightgbm_feature_importance(bundle.booster, list(bundle.feature_cols))
    generate_eval(
        ArtifactInputs(
            model_name=MODEL_NAME,
            model_version=inputs.model_version,
            class_labels=list(PITCH_TYPE_CLASSES),
            cv_result=inputs.cv_result,
            test_df=inputs.test_df,
            test_predictions=inputs.test_predictions,
            training_data_hash=data_hash,
            feature_importance=fi,
            segment_cols=_SEGMENT_COLS,
        ),
        out_dir,
    )
    log.info("persisted pitch_type_pre bundle to %s (snapshot %s)", out_dir, snapshot_path)
    return out_dir
