"""Production persistence for the pitch-type family (Phase 2a/2b, decision [183]).

Writes the canonical files the registry + ONNX export consume, into
``artifacts/<model_name>/<version>/``:

    model.lgb              LightGBM y7 booster        (pitch_type_pre)
    model.pkl              sklearn pipeline, joblib   (pitch_type_lr_baseline)
    calibrator.json        the single-scalar temperature calibrator
    feature_pipeline.json  copied from /contracts/feature_pipeline_pitchtype.json
    park_id_mapping.json   the loader's deterministic park_id -> int
    metadata.json          provenance (git sha, data hash, window, hyperparams, CV summary)
    training_data.parquet  the test-fold snapshot (ONNX-export parity + downstream eval)
    eval/                  generated by bullpen_training.eval.artifact

Both heads share ONE writer (:func:`_persist_bundle`) because rule 9 makes them a matched
pair: the [183] guardrail compares them on log-loss, so any divergence in how their evidence
is written is a divergence in the comparison. They differ only in the model artifact
(booster vs joblib pipeline), the feature-importance table (LightGBM gain has no LR analogue
on the same scale), and the LR's extra provenance.

Deliberately simpler than pitch.persist: pitch-type has NO target-encoding lookups (no
pitcher_te/batter_te) and calibrates with temperature (not per-class isotonic).
"""

from __future__ import annotations

import hashlib
import json
import logging
import shutil
import subprocess
from collections.abc import Callable
from dataclasses import dataclass
from datetime import UTC, datetime
from pathlib import Path
from typing import Any

import joblib
import numpy as np
import pandas as pd

from bullpen_training.eval.artifact import (
    ArtifactInputs,
    hash_dataframe,
    lightgbm_feature_importance,
)
from bullpen_training.eval.artifact import (
    generate as generate_eval,
)
from bullpen_training.eval.cv_harness import CVResult
from bullpen_training.pitch_type import PITCH_TYPE_CLASSES
from bullpen_training.pitch_type.contract import (
    CONTRACT_PATH,
    assert_declared_lookups_present,
    load_canonical_pipeline,
)
from bullpen_training.pitch_type.temperature import TemperatureCalibrator
from bullpen_training.pitch_type.train import UNKNOWN_PARK_CODE, ModelBundle
from bullpen_training.pitch_type.train_lr import LR_TRAIN_SUBSAMPLE_SEED, LRModelBundle

log = logging.getLogger(__name__)

REPO_ROOT = Path(__file__).resolve().parents[4]
DEFAULT_ARTIFACTS_DIR = REPO_ROOT / "training" / "artifacts"
MODEL_NAME = "pitch_type_pre"
LR_MODEL_NAME = "pitch_type_lr_baseline"
"""The rule-9 co-registered baseline. A SEPARATE registry row from MODEL_NAME (two models,
not one with a flag), sharing the same feature contract."""

# Segment the held-out eval by the loader's encoded column names (analogous to the
# pitch-outcome defaults); segment_metrics silently skips any that are absent.
_SEGMENT_COLS = ("throws_i", "stand_i", "park_i", "balls", "strikes", "inning")


@dataclass(frozen=True)
class PitchTypePersistInputs:
    model_version: str
    train_window: str
    val_window: str
    test_df: pd.DataFrame
    test_predictions: np.ndarray
    cv_result: CVResult
    hyperparams: dict[str, Any]
    park_id_mapping: dict[str, int] | None = None
    # The window the test_df snapshot covers. Recorded in metadata so the snapshot's hash is
    # never read as covering the training window it sits next to.
    test_window: str = ""


def _git_commit_sha() -> str:
    try:
        return subprocess.check_output(
            ["git", "rev-parse", "HEAD"], cwd=str(REPO_ROOT), text=True
        ).strip()
    except (subprocess.CalledProcessError, FileNotFoundError):
        return "unknown"


def _sha256_of_path(path: Path) -> str:
    h = hashlib.sha256()
    with path.open("rb") as fh:
        for chunk in iter(lambda: fh.read(8192), b""):
            h.update(chunk)
    return h.hexdigest()


def _supplementary_metrics(test_df: pd.DataFrame, test_predictions: np.ndarray) -> dict[str, Any]:
    """Decision [183]'s SUPPLEMENTARY (explicitly non-gating) accuracy figures.

    [183] locks the metric set as PRIMARY absolute ECE < 0.02, GUARDRAIL log-loss vs
    pitch_type_lr_baseline, and top-3 accuracy as a supplementary figure. Recording top-3
    here means the persisted evidence carries the whole declared set instead of leaving the
    only accuracy number in the bundle a per-segment TOP-1 - which, read alone, would
    misrepresent a calibrated prior as a next-pitch predictor.
    """
    y = np.asarray(test_df["label"], dtype=np.int64)
    p = np.asarray(test_predictions, dtype=np.float64)
    n_classes = p.shape[1]
    k = min(3, n_classes)
    # argpartition puts the k largest in the first k slots (unordered) - enough for a
    # membership test and cheaper than a full sort.
    top_k_idx = np.argpartition(-p, kth=k - 1, axis=1)[:, :k]
    return {
        "top1_accuracy": float((p.argmax(axis=1) == y).mean()),
        "top3_accuracy": float((top_k_idx == y[:, None]).any(axis=1).mean()),
        "note": (
            "Decision [183]: SUPPLEMENTARY, NOT gating. The promotion gate is absolute "
            "calibration (ECE < 0.02) with a log-loss guardrail vs pitch_type_lr_baseline. "
            "This model is a calibrated pitch-type PRIOR, not a top-1 next-pitch predictor."
        ),
    }


def _write_park_id_mapping(out_dir: Path, mapping: dict[str, int]) -> Path:
    """park_id -> int, sorted by key for byte-stability (mirrors pitch.persist's shape).

    ``missing_value`` is imported from the loader that produced the encoding, so the Python
    encoder and the JSON that tells Java how to encode cannot drift apart.
    """
    payload = {"park_id": dict(sorted(mapping.items())), "missing_value": UNKNOWN_PARK_CODE}
    path = out_dir / "park_id_mapping.json"
    path.write_text(json.dumps(payload, indent=2, sort_keys=False) + "\n")
    return path


def _write_metadata(
    out_dir: Path,
    inputs: PitchTypePersistInputs,
    model_path: Path,
    *,
    model_name: str,
    training_data_hash: str,
    calibrator_path: Path,
    schema_hash: str,
    snapshot_path: Path,
    phase: str,
    extras: dict[str, Any] | None = None,
) -> Path:
    payload: dict[str, Any] = {
        "model_name": model_name,
        # The Java load gate resolves a loader from the model's OWN metadata, never by model name
        # (ModelLoadValidator). pitch-type has neither park_order nor head, so without an explicit
        # kind it falls through to the batted-ball loader and every promotion 422s. This is the
        # first-class discriminator that class's follow-on note asks for.
        "model_kind": "pitch_type",
        "model_version": inputs.model_version,
        "phase": phase,
        "training_data_window": inputs.train_window,
        "val_window": inputs.val_window,
        # NB the snapshot (and therefore this hash) is the fold's held-out TEST window, not
        # the training window named above - it is what the ONNX-export parity check and the
        # downstream eval read. snapshot_window is recorded so the two are never conflated.
        "training_data_hash": training_data_hash,
        "snapshot": {
            "path": snapshot_path.name,
            "window": inputs.test_window,
            "rows": len(inputs.test_df),
            "sha256": _sha256_of_path(snapshot_path),
            "contents": "held-out test-fold rows (features + label)",
        },
        "model_artifact": {"path": model_path.name, "sha256": _sha256_of_path(model_path)},
        "calibrator": {
            "path": calibrator_path.name,
            "sha256": _sha256_of_path(calibrator_path),
            "kind": "temperature",
        },
        # schema_hash comes from the VERIFIED contract read (recomputed from file content,
        # rule 7), never the file's self-declared field - a stale contract must fail loud
        # here, not silently stamp a wrong hash that only registration would catch.
        "feature_pipeline_hash": schema_hash,
        "supplementary_metrics": _supplementary_metrics(inputs.test_df, inputs.test_predictions),
        "git_commit": _git_commit_sha(),
        "trained_at": datetime.now(UTC).isoformat(timespec="seconds"),
        "hyperparams": inputs.hyperparams,
        "eval_metrics_summary": {
            name: {"mean": mean, "std": std}
            for name, (mean, std) in inputs.cv_result.summary.items()
        },
        "eval_metrics_per_fold": [
            {
                "fold_id": fr.fold_id,
                "train_rows": fr.train_rows,
                "val_rows": fr.val_rows,
                "test_rows": fr.test_rows,
                "metrics": fr.metrics,
            }
            for fr in inputs.cv_result.per_fold
        ],
    }
    if extras:
        # Refuse to let a per-head extras key shadow an identity/provenance field. Silently
        # overwriting model_name or feature_pipeline_hash would produce a bundle whose
        # metadata lies about what it is - the one thing this file exists to get right.
        clashes = sorted(set(extras) & set(payload))
        if clashes:
            raise ValueError(f"metadata extras may not overwrite core fields: {clashes}")
        payload.update(extras)
    meta_path = out_dir / "metadata.json"
    meta_path.write_text(json.dumps(payload, indent=2, sort_keys=False) + "\n")
    return meta_path


def _persist_bundle(
    inputs: PitchTypePersistInputs,
    *,
    model_name: str,
    calibrator: TemperatureCalibrator,
    write_model: Callable[[Path], Path],
    feature_importance: pd.DataFrame | None,
    artifacts_dir: Path | None = None,
    metadata_extras: dict[str, Any] | None = None,
    phase: str = "2a",
) -> Path:
    """Write the canonical files + eval/ for either pitch-type head.

    Reads the contract through the VERIFIED loader (rule 7: recompute-and-fail-loud) BEFORE
    writing anything, and refuses to return a bundle missing any lookup file that contract
    declares - so an incomplete bundle fails here rather than at serving time.

    ``write_model`` receives the bundle directory and returns the path it wrote, which keeps
    the artifact format (LightGBM text vs joblib pickle) the ONLY thing the two heads differ
    on in this function.
    """
    spec = load_canonical_pipeline()
    base = artifacts_dir or DEFAULT_ARTIFACTS_DIR
    out_dir = base / model_name / inputs.model_version
    out_dir.mkdir(parents=True, exist_ok=True)

    model_path = write_model(out_dir)

    cal_path = out_dir / "calibrator.json"
    calibrator.to_json(cal_path)

    shutil.copyfile(CONTRACT_PATH, out_dir / "feature_pipeline.json")
    if inputs.park_id_mapping is not None:
        _write_park_id_mapping(out_dir, inputs.park_id_mapping)

    snapshot_path = out_dir / "training_data.parquet"
    inputs.test_df.to_parquet(snapshot_path, index=False)
    data_hash = hash_dataframe(inputs.test_df)

    _write_metadata(
        out_dir,
        inputs,
        model_path,
        model_name=model_name,
        training_data_hash=data_hash,
        calibrator_path=cal_path,
        schema_hash=spec["schema_hash"],
        snapshot_path=snapshot_path,
        phase=phase,
        extras=metadata_extras,
    )
    # Every side-car the copied contract declares must exist (park_id_mapping.json,
    # calibrator.json). A missing one means an unloadable bundle - fail loud, do not report
    # success on a bundle the serving path cannot consume.
    assert_declared_lookups_present(out_dir, spec)

    generate_eval(
        ArtifactInputs(
            model_name=model_name,
            model_version=inputs.model_version,
            class_labels=list(PITCH_TYPE_CLASSES),
            cv_result=inputs.cv_result,
            test_df=inputs.test_df,
            test_predictions=inputs.test_predictions,
            training_data_hash=data_hash,
            feature_importance=feature_importance,
            segment_cols=_SEGMENT_COLS,
        ),
        out_dir,
    )
    log.info("persisted %s bundle to %s (snapshot %s)", model_name, out_dir, snapshot_path)
    return out_dir


def persist_pitch_type_v1(
    bundle: ModelBundle,
    inputs: PitchTypePersistInputs,
    *,
    artifacts_dir: Path | None = None,
    metadata_extras: dict[str, Any] | None = None,
) -> Path:
    """Write the canonical files + eval/ for the pitch-type LightGBM bundle.

    ``metadata_extras`` carries the native drift baselines (``pitch_type.baselines``); additive
    keys only - ``_write_metadata`` refuses extras that shadow core fields.
    """

    def _write(out_dir: Path) -> Path:
        path = out_dir / "model.lgb"
        bundle.booster.save_model(str(path))
        return path

    return _persist_bundle(
        inputs,
        model_name=MODEL_NAME,
        calibrator=bundle.calibrator,
        write_model=_write,
        feature_importance=lightgbm_feature_importance(bundle.booster, list(bundle.feature_cols)),
        artifacts_dir=artifacts_dir,
        metadata_extras=metadata_extras,
    )


def persist_pitch_type_lr_v1(
    bundle: LRModelBundle,
    inputs: PitchTypePersistInputs,
    *,
    artifacts_dir: Path | None = None,
) -> Path:
    """Write the canonical files + eval/ for the rule-9 LR baseline.

    No ONNX export IN THIS STEP. Do not read that as "this model is never served": the
    registry serves every model through ONNX Runtime (``pitch.register_snapshot`` hardcodes
    ``ARTIFACT_FILE = "model.onnx"``, and ``pitch.export_lr_onnx`` exists for exactly this
    reason on the outcome head). Since the [182] first-champion gate binds its champion to a
    REGISTERED version of this model, a registry-facing skl2onnx export is a required
    follow-up before Phase 3, not an optional one.

    No feature-importance table either: LR coefficients are not on the same scale as LightGBM
    gain, so emitting one under the same filename would invite a false comparison.
    """

    def _write(out_dir: Path) -> Path:
        path = out_dir / "model.pkl"
        joblib.dump(bundle.pipeline, path)
        return path

    extras: dict[str, Any] = {
        "fitted_label_classes": list(bundle.fitted_label_classes),
        "design_matrix_dtype": "float32",
        "calibrator_family_rationale": (
            "temperature, matching pitch_type_pre rather than the pitch-outcome baseline's "
            "isotonic. Decision [183]'s guardrail compares log-loss between this model and "
            "pitch_type_pre, so a different calibration family on each side would make that "
            "comparison partly a measurement of the calibrators."
        ),
    }
    if bundle.train_subsample_rows is not None:
        extras["lr_train_subsample_rows"] = bundle.train_subsample_rows
        extras["lr_train_rows_before_subsample"] = bundle.train_rows_before_subsample
        extras["lr_train_subsample_seed"] = LR_TRAIN_SUBSAMPLE_SEED
        extras["lr_train_subsample_rationale"] = (
            "baseline-only memory accommodation: lbfgs upcasts the design matrix to float64 "
            "internally, so the full fold-4 window exceeds box headroom (~13.7 GB peak "
            "MEASURED on pitch_outcome_lr_baseline at 31 features, inherited here rather "
            "than re-measured for this 24-feature head). Fixed-seed row "
            "sample WITHIN the fixed temporal window - NOT a re-split, and not a random "
            "train/test partition (CLAUDE.md rule 10). The CV folds are NOT subsampled, and "
            "the test WINDOW is scored in full - but the predictions scoring it come from "
            "this subsampled fit, so the retained fraction is recorded above rather than "
            "left for a reader to infer."
        )

    return _persist_bundle(
        inputs,
        model_name=LR_MODEL_NAME,
        calibrator=bundle.calibrator,
        write_model=_write,
        feature_importance=None,
        artifacts_dir=artifacts_dir,
        metadata_extras=extras,
        phase="2b",
    )
