"""Generate deterministic toy artifacts + parity fixture for CI.

Phase 1's parity tests need real model.onnx + park_hr_rate.json +
fixture JSONs to assert against. The dev path (1.3 + 1.4) requires
ClickHouse + pybaseball + a full 2024 season pull — too heavy and too
flaky for CI.

This script produces a byte-stable equivalent from pure synthetic data:

    1. Generate a small synthetic in-play DataFrame (no CH, no pybaseball)
    2. Train a tiny LightGBM model on it
    3. Export to ONNX through the same `export()` we use in dev (which
       validates against /contracts/feature_pipeline_toy.json)
    4. Write a small parity fixture (input rows + expected probs)

Re-runs are byte-identical so cache-hit reuse is safe. The committed
fixture in tests/fixtures/ is NOT regenerated by this script (CI
diff-checks would flag noise); it's regenerated only when you re-run
parity_fixture.py against real CH data and explicitly commit it.

CI uses this script before:
  - pytest tests/battedball/test_python_java_parity.py  (Python side)
  - ./gradlew test --tests 'ToyParityTest'              (Java side)
"""

from __future__ import annotations

import json
import logging
import os
from pathlib import Path
from typing import Any, cast

import click
import lightgbm as lgb
import numpy as np
import pandas as pd

from bullpen_training.battedball.export_toy_onnx import export
from bullpen_training.battedball.features_toy import FEATURES, TARGET
from bullpen_training.battedball.train_toy import (
    DEFAULT_OUTPUT_DIR,
    _train_on_frame,
)
from bullpen_training.logging_config import configure_logging, get_logger

log = get_logger(__name__)

CI_SEED = 1337

# Subset of MLB park codes for the synthetic lookup — keeps the fixture
# shape close to prod (target-encoded park_id is a real feature).
SYNTHETIC_PARKS: tuple[str, ...] = (
    "ATL",
    "BAL",
    "BOS",
    "CHC",
    "CIN",
    "CLE",
    "COL",
    "DET",
    "HOU",
    "KC",
    "LAA",
    "LAD",
    "MIA",
    "MIL",
    "MIN",
    "NYM",
    "NYY",
    "OAK",
    "PHI",
    "PIT",
    "SD",
    "SEA",
    "SF",
    "STL",
    "TB",
    "TEX",
    "TOR",
    "WSH",
    "AZ",
    "CHW",
)


def synthesize_in_play_frame(n: int = 4000) -> pd.DataFrame:
    """Synthetic in-play distribution: launch_speed Uniform[40,115], launch_angle
    Uniform[-30,60], release_speed Uniform[70,100], park uniformly sampled,
    50/50 L/R stand. `is_hr` is a deterministic function of (speed, angle)
    plus a small ballpark factor — gives the model real signal to learn so
    the parity test exercises a real prediction surface.
    """
    rng = np.random.default_rng(CI_SEED)
    n_rows = n
    df = pd.DataFrame(
        {
            "launch_speed_mph": rng.uniform(40, 115, n_rows).astype("float32"),
            "launch_angle_deg": rng.uniform(-30, 60, n_rows).astype("float32"),
            "release_speed_mph": rng.uniform(70, 100, n_rows).astype("float32"),
            "park_id": rng.choice(SYNTHETIC_PARKS, n_rows),
            "stand": rng.choice(["L", "R"], n_rows),
        }
    )
    park_factor: dict[str, float] = {p: 0.02 + 0.001 * i for i, p in enumerate(SYNTHETIC_PARKS)}
    df["park_id_encoded"] = df["park_id"].map(park_factor.get).astype("float32")
    df["stand_is_left"] = (df["stand"] == "L").astype("int8")
    hr_signal = ((df["launch_speed_mph"] > 95) & df["launch_angle_deg"].between(20, 40)).astype(
        "float32"
    )
    noise = rng.uniform(0, 1, n_rows) < (0.05 + df["park_id_encoded"])
    df[TARGET] = ((hr_signal > 0) | noise).astype("uint8")
    return df


def _save_model_lgb(df: pd.DataFrame, outdir: Path) -> dict[str, Any]:
    outdir.mkdir(parents=True, exist_ok=True)
    training_frame = cast(pd.DataFrame, df[[*FEATURES, TARGET]])
    booster, metrics = _train_on_frame(training_frame)
    model_path = outdir / "model.lgb"
    booster.save_model(str(model_path))
    return {"metrics": metrics, "model_path": str(model_path)}


def _write_metadata(outdir: Path, *, train_summary: dict[str, Any], schema_hash: str) -> None:
    """Emit metadata.json for the toy model.

    InferenceRouterIT.registerToyVersion copies this file alongside model.onnx +
    feature_pipeline.json to register toy versions, so it must exist in a fresh
    CI checkout — not only as a leftover from an old local training run. The
    generator previously wrote model.onnx + park_hr_rate.json + the parity
    fixtures but NOT metadata.json, so the IT failed with NoSuchFileException on
    CI (where artifacts are regenerated from scratch)."""
    metrics = train_summary["metrics"]
    metadata = {
        "model_name": "_toy_batted_ball",
        "version": "v0",
        "phase": "ci-synthetic",
        "features": list(FEATURES),
        "target": TARGET,
        "schema_hash": schema_hash,
        "metrics": metrics,
        "registry_status": "ci-synthetic (regenerated by generate_ci_artifacts)",
    }
    (outdir / "metadata.json").write_text(json.dumps(metadata, indent=2) + "\n")


def _write_park_lookup(df: pd.DataFrame, outdir: Path) -> dict[str, float]:
    """Build the park_hr_rate.json from the synthetic frame so the lookup
    keys agree with the data the parity fixture rows are drawn from."""
    rate_series = cast(pd.Series, df.groupby("park_id")[TARGET].mean())
    lookup = {str(k): float(v) for k, v in sorted(rate_series.items())}
    (outdir / "park_hr_rate.json").write_text(json.dumps(lookup, indent=2) + "\n")
    return lookup


def _write_parity_fixture(
    df: pd.DataFrame,
    *,
    booster_path: Path,
    onnx_path: Path,
    park_lookup: dict[str, float],
    schema_hash: str,
    fixture_dir: Path,
    n: int = 16,
) -> None:
    """Pick n rows, run them through both the in-process booster and the
    exported ONNX, and write the two-file parity fixture."""
    import onnxruntime as ort  # local import keeps test envs lean

    from bullpen_training.battedball.parity_fixture import (
        _onnx_probability,
        _preprocess,
    )

    booster = lgb.Booster(model_file=str(booster_path))
    session = ort.InferenceSession(str(onnx_path))

    sample = df.sort_values(
        ["launch_speed_mph", "launch_angle_deg"], ascending=[False, False]
    ).head(n)

    inputs: list[dict[str, Any]] = []
    expected: list[dict[str, Any]] = []
    for idx, raw_row in enumerate(sample.to_dict(orient="records")):
        row: dict[str, Any] = {
            "game_id": 700000 + idx,
            "at_bat_index": idx % 12,
            "pitch_number": (idx % 5) + 1,
            "game_date": "2024-07-04",
            "home_team": str(raw_row["park_id"]),
            "park_id": str(raw_row["park_id"]),
            "stand": str(raw_row["stand"]),
            "launch_speed_mph": float(raw_row["launch_speed_mph"]),
            "launch_angle_deg": float(raw_row["launch_angle_deg"]),
            "release_speed_mph": float(raw_row["release_speed_mph"]),
            "is_hr": int(raw_row["is_hr"]),
        }
        vector = _preprocess(row, park_lookup)
        onnx_prob = _onnx_probability(session, vector)
        lgb_pred = cast(np.ndarray, booster.predict(np.array([vector], dtype=np.float32)))
        expected.append(
            {
                "game_id": row["game_id"],
                "at_bat_index": row["at_bat_index"],
                "pitch_number": row["pitch_number"],
                "feature_vector": vector,
                "onnx_probability": onnx_prob,
                "lightgbm_probability": float(lgb_pred[0]),
                "abs_difference_onnx_lightgbm": abs(onnx_prob - float(lgb_pred[0])),
            }
        )
        inputs.append(row)

    fixture_dir.mkdir(parents=True, exist_ok=True)
    (fixture_dir / "parity_toy_001.json").write_text(
        json.dumps(
            {
                "model_name": "_toy_batted_ball",
                "version": "v0",
                "feature_order": list(FEATURES),
                "schema_hash": schema_hash,
                "rows": inputs,
            },
            indent=2,
        )
        + "\n"
    )
    (fixture_dir / "parity_toy_001_expected.json").write_text(
        json.dumps(
            {
                "model_name": "_toy_batted_ball",
                "version": "v0",
                "schema_hash": schema_hash,
                "tolerance": 1e-6,
                "rows": expected,
            },
            indent=2,
        )
        + "\n"
    )


def generate(
    *,
    output_dir: Path | None = None,
    fixture_dir: Path | None = None,
    n_synthetic: int = 4000,
    n_fixture: int = 16,
    write_fixture: bool = False,
) -> dict[str, Any]:
    outdir = output_dir or DEFAULT_OUTPUT_DIR
    fdir = fixture_dir or (Path(__file__).resolve().parents[3] / "tests" / "fixtures")

    df = synthesize_in_play_frame(n_synthetic)
    train_summary = _save_model_lgb(df, outdir)
    park_lookup = _write_park_lookup(df, outdir)
    export_summary = export(output_dir=outdir, park_hr_rate=park_lookup)
    _write_metadata(outdir, train_summary=train_summary, schema_hash=export_summary["schema_hash"])
    if write_fixture:
        _write_parity_fixture(
            df,
            booster_path=outdir / "model.lgb",
            onnx_path=outdir / "model.onnx",
            park_lookup=park_lookup,
            schema_hash=export_summary["schema_hash"],
            fixture_dir=fdir,
            n=n_fixture,
        )
    summary = {
        "synthetic_rows": len(df),
        "hr_rate": float(cast(pd.Series, df[TARGET]).mean()),
        "model_auc": train_summary["metrics"]["auc"],
        "park_lookup_entries": len(park_lookup),
        "onnx_path": export_summary["onnx_path"],
        "schema_hash": export_summary["schema_hash"],
        "fixture_written": write_fixture,
    }
    log.info("CI artifacts ready", **summary)
    return summary


@click.command()
@click.option(
    "--out-dir",
    type=click.Path(file_okay=False, dir_okay=True, path_type=Path),
    default=None,
)
@click.option(
    "--fixture-dir",
    type=click.Path(file_okay=False, dir_okay=True, path_type=Path),
    default=None,
)
@click.option("--n-synthetic", type=int, default=4000, show_default=True)
@click.option("--n-fixture", type=int, default=16, show_default=True)
@click.option(
    "--write-fixture",
    is_flag=True,
    help="Also overwrite tests/fixtures/parity_toy_001*.json. CI normally does NOT pass this.",
)
@click.option(
    "--log-format",
    type=click.Choice(["console", "json"], case_sensitive=False),
    default="console",
)
def main(
    out_dir: Path | None,
    fixture_dir: Path | None,
    n_synthetic: int,
    n_fixture: int,
    write_fixture: bool,
    log_format: str,
) -> None:
    if log_format.lower() == "json":
        os.environ["LOG_FORMAT"] = "json"
    configure_logging(level=logging.INFO)
    generate(
        output_dir=out_dir,
        fixture_dir=fixture_dir,
        n_synthetic=n_synthetic,
        n_fixture=n_fixture,
        write_fixture=write_fixture,
    )


if __name__ == "__main__":
    main()
