package net.thebullpen.baseball.domain;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.within;

import org.junit.jupiter.api.Test;

/**
 * Cross-language parity for the spray derivation.
 *
 * <p>THE GAP THIS CLOSES. The served batted-ball model was trained on {@code
 * battedball/features_shared.py:hc_to_spray_deg}, and Java's feature pipeline passes {@code
 * spray_angle_deg} through unmodified - so the Java derivation is not "similar to" the Python one,
 * it must BE it. A version shipped briefly with the sign inverted and a plate constant (199.53)
 * that exists nowhere in training or {@code contracts/}, and every live batted ball was scored as
 * though hit to the opposite field.
 *
 * <p>Nothing on the Java side could have caught that: javac, ArchUnit and every backend test saw a
 * self-consistent record, because the contradiction existed only across the boundary. This is the
 * same shape as the feature-schema-hash parity the project already enforces between Python and Java
 * under rule 7 - a derivation that must match training belongs under that discipline, and this one
 * was not.
 *
 * <p>EXPECTED VALUES WERE COMPUTED BY THE PYTHON, not re-derived here. Re-deriving them in Java
 * would make this test agree with whatever Java does - the shared-oracle trap. To regenerate:
 *
 * <pre>
 *   uv run python -c "from bullpen_training.battedball.features_shared import hc_to_spray_deg as t; \
 *     print(t(196.18, 65.51))"
 * </pre>
 */
class BattedBallSprayParityTest {

  /** hc_x, hc_y, and the value hc_to_spray_deg returns for them. */
  private static final double[][] FROM_PYTHON = {
    // Generated by the Python, verbatim - see the regeneration command above. Two of these were
    // originally transcribed from a 2-decimal display and padded with invented digits, and the test
    // caught it: taking values FROM the source only works if you actually take them from it.
    {196.18, 65.51, -28.057253}, // home run to right field - NEGATIVE in this convention
    {150.15, 153.92, -29.144471}, // groundout
    {184.99, 112.47, -34.771824}, // single
    {126.60, 88.40, -0.615331}, // essentially up the middle
    {95.00, 70.00, +13.341560}, // pulled to LEFT field - POSITIVE
  };

  @Test
  void matchesTrainingsDerivationInBothMagnitudeAndSIGN() {
    for (double[] row : FROM_PYTHON) {
      double actual = BattedBall.sprayAngleDeg(row[0], row[1]).orElseThrow();
      assertThat(actual)
          .as("hc(%.2f, %.2f) must match hc_to_spray_deg", row[0], row[1])
          .isCloseTo(row[2], within(1e-6));
    }
  }

  @Test
  void positiveIsTowardLeftFieldNotRight() {
    // The single assertion that would have caught the shipped defect. Magnitudes were correct
    // throughout; only the sign was wrong, so any test comparing absolute values would have passed.
    double pulledLeft = BattedBall.sprayAngleDeg(95.0, 70.0).orElseThrow();
    double pushedRight = BattedBall.sprayAngleDeg(196.18, 65.51).orElseThrow();
    assertThat(pulledLeft).as("toward 3B/LF is POSITIVE in training's convention").isPositive();
    assertThat(pushedRight).as("toward 1B/RF is NEGATIVE").isNegative();
  }

  @Test
  void usesThePublishedPlateConstantsTrainingUses() {
    // Pins the constants indirectly but decisively: at the plate itself the derivation is
    // degenerate, and it is degenerate at (125.42, 198.27) specifically. With the 199.53 that
    // shipped, this point has towardOutfield = 1.26 and returns a value instead of declining.
    assertThat(BattedBall.sprayAngleDeg(125.42, 198.27))
        .as("(125.42, 198.27) is the plate - the derivation must decline there")
        .isEmpty();
  }
}
