/**
 * Matchup Report fixture data — the signature scouting-packet page of the
 * scouting-report identity (per decision [133]). Used by the Matchup Report at
 * /players/:id while the real player → pitch-mix / spray / calibration plumbing
 * is offline.
 *
 * Five batter-vs-pitcher symmetric pairings are hard-coded so any player route
 * (`/players/judge_aaron`, `/players/skubal_tarik`, etc.) lands on a
 * fully-populated, visually-credible report. Unknown ids fall back to
 * Judge → Skubal.
 *
 * Density grids (pitch-location heatmaps + spray-chart zones) are generated by
 * a small 2-D Gaussian helper {@link makeGrid} so the bumps line up with the
 * documented peak locations in spec §11 (FF top-of-zone, SL low-arm-side,
 * CB low-glove-side, CH down-arm-side). Outputs are normalized to [0, 1] so
 * the heatmap component can rescale linearly without per-grid bookkeeping.
 *
 * All numbers are plausible MLB-range values (PA, xwOBA, K%, etc.) but are
 * NOT real data — clearly fictionalised for the redesign demo. The shapes
 * match the eventual API contracts so the page swap from fixture → live data
 * later is component-internal only.
 */

import type { MetricMeta } from "../design/cellColor";

// ── Types (spec §11) ─────────────────────────────────────────────────────────

export type Hand = "L" | "R" | "S";

export type Grade = {
  /** Display label, e.g. "Power", "Contact". */
  label: string;
  /** 20–80 scouting scale; null = no grade. */
  value: number | null;
};

export type ScoutingPlayer = {
  /** Slug id used in URLs (e.g. "judge_aaron"). */
  id: string;
  /** Display name, "First Last". */
  name: string;
  /** Position, e.g. "RF", "SP". */
  position: string;
  /** Bats / throws hand string, e.g. "R/R" or "L/L". */
  hand: string;
  /** Jersey number as a string for tabular alignment. */
  jersey: string;
  /** Team abbreviation, e.g. "NYY". */
  team: string;
  /** Age. */
  age: number;
  /** Listed height. */
  height: string;
  /** Listed weight in lbs. */
  weight: number;
  /** Two- or three-line headline summary above the grades. */
  summary: string;
  /** Ordered list of grade rows. */
  grades: Grade[];
};

/** One row in the pitcher pitch-mix StatTable. */
export type PitchMixRow = {
  /** "FF", "SL", "CB", "CH", "SI", "FC". */
  code: string;
  /** Display name, e.g. "Four-seam". */
  name: string;
  /** Usage %, 0..1. */
  usage: number;
  /** Average velo, mph. */
  velo: number;
  /** Whiff rate vs the batter's hand, 0..1. */
  whiff: number;
  /** xwOBA against, MLB-range. */
  xwoba: number;
  /** Put-away rate (K's / 2-strike), 0..1. */
  putaway: number;
  /** Location density grid, row-major, [0..1]. 12×12. */
  locationGrid: number[][];
};

/** One row in the batter splits StatTable. */
export type SplitRow = {
  /** Split label, e.g. "vs LHP", "vs RHP", "Bases empty". */
  split: string;
  pa: number;
  avg: number;
  obp: number;
  slg: number;
  iso: number;
  xwoba: number;
  k: number;
  bb: number;
};

/** One spray-chart zone summary. */
export type SprayZone = {
  /** Zone id, e.g. "LF-pull", "CF", "RF-oppo". */
  id: string;
  /** Display label. */
  label: string;
  /** Number of batted balls landing here. */
  count: number;
  /** Density 0..1 — used for the cell tint AND a numeric annotation. */
  density: number;
};

/** One recent prediction row. */
export type MatchupPrediction = {
  /** ISO-8601 instant. */
  when: string;
  /** What the model predicted, free-form ("Single", "K-swinging", etc.). */
  predicted: string;
  /** Model probability for the predicted class, 0..1. */
  prob: number;
  /** Observed outcome (free-form). */
  actual: string;
  /** Whether predicted matched actual. */
  agreed: boolean;
};

/** Calibration bin for the reliability diagram. */
export type CalibrationBin = {
  binStart: number;
  binEnd: number;
  predicted: number;
  actual: number;
  n: number;
};

/** A fully resolved Matchup Report (right-side player + opposing-side player). */
export type MatchupReport = {
  /** The player whose route we landed on. */
  primary: ScoutingPlayer;
  /** The opposing-side player. */
  opponent: ScoutingPlayer;
  /** Pitch-mix rows belong to whichever side is the pitcher. */
  pitcherMix: PitchMixRow[];
  /** Splits rows belong to whichever side is the batter. */
  batterSplits: SplitRow[];
  /** Spray chart zones for the batter. */
  spray: SprayZone[];
  /** Recent matchup-context predictions. */
  predictions: MatchupPrediction[];
  /** Calibration bins for the pitch-outcome model on this matchup. */
  calibration: CalibrationBin[];
  /** Free-form key-notes paragraphs (≤ 3). */
  keyNotes: string[];
  /** Headline date / game context. */
  context: string;
};

// ── Metric meta (cellColor references) ───────────────────────────────────────

/**
 * Metric metadata registry. Every numeric column that participates in
 * conditional formatting reaches in here for its MetricMeta — so the cellColor
 * percentile mapping is consistent across StatTable and PlayerProfileCard.
 *
 * Reference distributions are MLB-typical ranges for the named metric.
 */
export const METRIC_META: Record<string, MetricMeta> = {
  usage: {
    key: "usage",
    direction: "higher-is-better",
    reference: { min: 0.02, p25: 0.1, median: 0.18, p75: 0.32, max: 0.6 },
  },
  velo: {
    key: "velo",
    direction: "higher-is-better",
    reference: { min: 70, p25: 84, median: 92, p75: 95, max: 102 },
  },
  whiff: {
    key: "whiff",
    direction: "higher-is-better",
    reference: { min: 0.05, p25: 0.18, median: 0.26, p75: 0.34, max: 0.55 },
  },
  xwoba_vs: {
    // pitcher's xwOBA-against: lower is better.
    key: "xwoba_vs",
    direction: "lower-is-better",
    reference: { min: 0.18, p25: 0.27, median: 0.32, p75: 0.36, max: 0.5 },
  },
  putaway: {
    key: "putaway",
    direction: "higher-is-better",
    reference: { min: 0.05, p25: 0.14, median: 0.2, p75: 0.27, max: 0.45 },
  },
  pa: {
    // Larger-sample columns: do NOT heat-format. Kept here for callers that
    // want it anyway.
    key: "pa",
    direction: "higher-is-better",
    reference: { min: 0, p25: 50, median: 200, p75: 400, max: 700 },
  },
  avg: {
    key: "avg",
    direction: "higher-is-better",
    reference: { min: 0.15, p25: 0.22, median: 0.255, p75: 0.285, max: 0.36 },
  },
  obp: {
    key: "obp",
    direction: "higher-is-better",
    reference: { min: 0.22, p25: 0.295, median: 0.325, p75: 0.36, max: 0.45 },
  },
  slg: {
    key: "slg",
    direction: "higher-is-better",
    reference: { min: 0.28, p25: 0.38, median: 0.42, p75: 0.47, max: 0.65 },
  },
  iso: {
    key: "iso",
    direction: "higher-is-better",
    reference: { min: 0.06, p25: 0.13, median: 0.17, p75: 0.22, max: 0.34 },
  },
  xwoba_batter: {
    key: "xwoba_batter",
    direction: "higher-is-better",
    reference: { min: 0.22, p25: 0.31, median: 0.34, p75: 0.38, max: 0.48 },
  },
  k: {
    // batter K%: lower is better.
    key: "k",
    direction: "lower-is-better",
    reference: { min: 0.1, p25: 0.18, median: 0.22, p75: 0.27, max: 0.38 },
  },
  bb: {
    key: "bb",
    direction: "higher-is-better",
    reference: { min: 0.04, p25: 0.07, median: 0.085, p75: 0.105, max: 0.18 },
  },
  // 20-80 scouting grades — clamp to a sensible range.
  grade: {
    key: "grade",
    direction: "higher-is-better",
    reference: { min: 20, p25: 40, median: 50, p75: 60, max: 80 },
  },
};

// ── Gaussian density helper ──────────────────────────────────────────────────

const GRID_SIZE = 12;

/**
 * Generate a 12×12 density grid with a 2-D Gaussian bump centered at
 * (peakRow, peakCol). Output values are normalized so the grid's maximum is
 * exactly 1.0 and the minimum is ≥ 0.0 (no negatives, no NaNs).
 *
 * Sigma is in grid-cell units. Sigma 1.5–2.0 reads as a focused pitch
 * tendency; sigma 3.0+ reads as a wider area.
 *
 * Used for both pitch-location heatmaps (peak = the pitcher's pitch's
 * preferred zone) and spray-chart density (peak = the batter's preferred
 * sector, expressed as a grid coordinate that the SprayChart projects onto
 * the field outline).
 */
export function makeGrid(
  peakRow: number,
  peakCol: number,
  sigma: number,
): number[][] {
  const grid: number[][] = [];
  let max = 0;
  for (let r = 0; r < GRID_SIZE; r++) {
    const row: number[] = [];
    for (let c = 0; c < GRID_SIZE; c++) {
      const dr = r - peakRow;
      const dc = c - peakCol;
      const val = Math.exp(-(dr * dr + dc * dc) / (2 * sigma * sigma));
      row.push(val);
      if (val > max) max = val;
    }
    grid.push(row);
  }
  // Normalize so the global max is 1.0.
  if (max > 0) {
    for (let r = 0; r < GRID_SIZE; r++) {
      for (let c = 0; c < GRID_SIZE; c++) {
        grid[r][c] = grid[r][c] / max;
      }
    }
  }
  return grid;
}

// ── Player registry ──────────────────────────────────────────────────────────

/**
 * Five batters + five pitchers. Each has a scouting-style summary + grades.
 * The matchup graph below pairs them symmetrically: route to either side and
 * the report renders the same matchup.
 */
export const PLAYERS: Record<string, ScoutingPlayer> = {
  judge_aaron: {
    id: "judge_aaron",
    name: "Aaron Judge",
    position: "RF",
    hand: "R/R",
    jersey: "99",
    team: "NYY",
    age: 33,
    height: "6'7\"",
    weight: 282,
    summary:
      "Premier right-handed power threat. Elite barrel rate; extreme pull-side authority on inner-half heaters.",
    grades: [
      { label: "Hit", value: 60 },
      { label: "Power", value: 80 },
      { label: "Run", value: 45 },
      { label: "Arm", value: 65 },
      { label: "Field", value: 55 },
    ],
  },
  trout_mike: {
    id: "trout_mike",
    name: "Mike Trout",
    position: "CF",
    hand: "R/R",
    jersey: "27",
    team: "LAA",
    age: 34,
    height: "6'2\"",
    weight: 235,
    summary:
      "Generational all-around hitter, still elite against right-handed velocity when healthy. Disciplined zone control.",
    grades: [
      { label: "Hit", value: 70 },
      { label: "Power", value: 70 },
      { label: "Run", value: 55 },
      { label: "Arm", value: 60 },
      { label: "Field", value: 60 },
    ],
  },
  soto_juan: {
    id: "soto_juan",
    name: "Juan Soto",
    position: "RF",
    hand: "L/L",
    jersey: "22",
    team: "NYM",
    age: 27,
    height: "6'2\"",
    weight: 224,
    summary:
      "Best plate discipline of his generation. Punishes left-handed pitching unusually well for an L/L bat.",
    grades: [
      { label: "Hit", value: 70 },
      { label: "Power", value: 70 },
      { label: "Run", value: 50 },
      { label: "Arm", value: 60 },
      { label: "Field", value: 50 },
    ],
  },
  ohtani_shohei: {
    id: "ohtani_shohei",
    name: "Shohei Ohtani",
    position: "DH",
    hand: "L/R",
    jersey: "17",
    team: "LAD",
    age: 31,
    height: "6'4\"",
    weight: 210,
    summary:
      "Left-handed hitter with elite pull-side power and top-decile chase discipline against premium velocity.",
    grades: [
      { label: "Hit", value: 65 },
      { label: "Power", value: 80 },
      { label: "Run", value: 60 },
      { label: "Arm", value: 70 },
      { label: "Field", value: 50 },
    ],
  },
  bichette_bo: {
    id: "bichette_bo",
    name: "Bo Bichette",
    position: "SS",
    hand: "R/R",
    jersey: "11",
    team: "TOR",
    age: 27,
    height: "6'0\"",
    weight: 200,
    summary:
      "Aggressive contact-first profile, drives the ball gap-to-gap. Vulnerable to elevated heat and front-foot breaking pitches.",
    grades: [
      { label: "Hit", value: 60 },
      { label: "Power", value: 55 },
      { label: "Run", value: 55 },
      { label: "Arm", value: 60 },
      { label: "Field", value: 50 },
    ],
  },
  skubal_tarik: {
    id: "skubal_tarik",
    name: "Tarik Skubal",
    position: "SP",
    hand: "L/L",
    jersey: "29",
    team: "DET",
    age: 28,
    height: "6'3\"",
    weight: 240,
    summary:
      "Elite left-handed starter. Four-pitch mix headlined by a 97-mph four-seamer up and a wipeout slider down-and-arm-side.",
    grades: [
      { label: "FB", value: 70 },
      { label: "SL", value: 70 },
      { label: "CB", value: 55 },
      { label: "CH", value: 60 },
      { label: "Ctrl", value: 65 },
    ],
  },
  cole_gerrit: {
    id: "cole_gerrit",
    name: "Gerrit Cole",
    position: "SP",
    hand: "R/R",
    jersey: "45",
    team: "NYY",
    age: 35,
    height: "6'4\"",
    weight: 220,
    summary:
      "Premier right-handed starter. Four-seam / slider / knuckle-curve mix; pounds the top of the zone with a 96-mph heater.",
    grades: [
      { label: "FB", value: 70 },
      { label: "SL", value: 65 },
      { label: "CB", value: 65 },
      { label: "CH", value: 55 },
      { label: "Ctrl", value: 70 },
    ],
  },
  skenes_paul: {
    id: "skenes_paul",
    name: "Paul Skenes",
    position: "SP",
    hand: "R/R",
    jersey: "30",
    team: "PIT",
    age: 23,
    height: "6'6\"",
    weight: 235,
    summary:
      "Top-of-rotation right-hander. 99-mph four-seamer paired with a 94-mph splinker; missed-bat profile vs both sides of the plate.",
    grades: [
      { label: "FB", value: 80 },
      { label: "SL", value: 65 },
      { label: "CB", value: 60 },
      { label: "CH", value: 70 },
      { label: "Ctrl", value: 60 },
    ],
  },
  burnes_corbin: {
    id: "burnes_corbin",
    name: "Corbin Burnes",
    position: "SP",
    hand: "R/R",
    jersey: "39",
    team: "BAL",
    age: 31,
    height: "6'3\"",
    weight: 225,
    summary:
      "Cutter-led right-hander. Elite spin profile; tunnels his cutter and curveball off identical release points.",
    grades: [
      { label: "FB", value: 65 },
      { label: "SL", value: 60 },
      { label: "CB", value: 70 },
      { label: "CH", value: 50 },
      { label: "Ctrl", value: 70 },
    ],
  },
  strider_spencer: {
    id: "strider_spencer",
    name: "Spencer Strider",
    position: "SP",
    hand: "R/R",
    jersey: "99",
    team: "ATL",
    age: 27,
    height: "6'0\"",
    weight: 195,
    summary:
      "Power right-hander. Two-pitch ace profile (98-mph four-seamer + low-80s slider); among MLB leaders in K%.",
    grades: [
      { label: "FB", value: 75 },
      { label: "SL", value: 75 },
      { label: "CB", value: 40 },
      { label: "CH", value: 45 },
      { label: "Ctrl", value: 60 },
    ],
  },
};

// ── Pitch-mix data per pitcher ───────────────────────────────────────────────

/**
 * Skubal pitch-mix: four-seamer up, slider low-arm-side (for an LHP, arm-side
 * is to the batter's outer half against an R bat), curve low-glove-side,
 * change down-arm-side. Grid is 12×12 with (0,0) at top-left = up-and-glove
 * from the catcher's POV. So "top-of-zone" peaks at small row, "arm-side"
 * peaks at large col for an LHP throwing to an RHB.
 */
const SKUBAL_MIX: PitchMixRow[] = [
  {
    code: "FF",
    name: "Four-seam",
    usage: 0.42,
    velo: 97.1,
    whiff: 0.31,
    xwoba: 0.29,
    putaway: 0.24,
    // FF: top of zone, slightly arm-side (col ~7-8 for LHP vs RHB).
    locationGrid: makeGrid(2, 7, 1.8),
  },
  {
    code: "SL",
    name: "Slider",
    usage: 0.27,
    velo: 88.4,
    whiff: 0.41,
    xwoba: 0.24,
    putaway: 0.33,
    // SL: low-arm-side.
    locationGrid: makeGrid(9, 8, 1.8),
  },
  {
    code: "CB",
    name: "Curveball",
    usage: 0.14,
    velo: 81.2,
    whiff: 0.32,
    xwoba: 0.27,
    putaway: 0.22,
    // CB: low-glove-side.
    locationGrid: makeGrid(9, 3, 2.0),
  },
  {
    code: "CH",
    name: "Changeup",
    usage: 0.17,
    velo: 86.8,
    whiff: 0.36,
    xwoba: 0.26,
    putaway: 0.27,
    // CH: down-arm-side.
    locationGrid: makeGrid(8, 9, 1.9),
  },
];

const COLE_MIX: PitchMixRow[] = [
  {
    code: "FF",
    name: "Four-seam",
    usage: 0.49,
    velo: 96.3,
    whiff: 0.28,
    xwoba: 0.31,
    putaway: 0.22,
    locationGrid: makeGrid(2, 5, 1.8),
  },
  {
    code: "SL",
    name: "Slider",
    usage: 0.22,
    velo: 87.1,
    whiff: 0.39,
    xwoba: 0.26,
    putaway: 0.31,
    locationGrid: makeGrid(8, 3, 1.7),
  },
  {
    code: "CB",
    name: "Knuckle-curve",
    usage: 0.18,
    velo: 84.6,
    whiff: 0.34,
    xwoba: 0.28,
    putaway: 0.26,
    locationGrid: makeGrid(9, 6, 2.0),
  },
  {
    code: "CH",
    name: "Changeup",
    usage: 0.11,
    velo: 88.5,
    whiff: 0.3,
    xwoba: 0.3,
    putaway: 0.21,
    locationGrid: makeGrid(8, 8, 2.0),
  },
];

const SKENES_MIX: PitchMixRow[] = [
  {
    code: "FF",
    name: "Four-seam",
    usage: 0.38,
    velo: 99.2,
    whiff: 0.33,
    xwoba: 0.27,
    putaway: 0.28,
    locationGrid: makeGrid(2, 6, 1.6),
  },
  {
    code: "SI",
    name: "Splinker",
    usage: 0.24,
    velo: 94.3,
    whiff: 0.27,
    xwoba: 0.25,
    putaway: 0.22,
    locationGrid: makeGrid(9, 4, 1.8),
  },
  {
    code: "SL",
    name: "Slider",
    usage: 0.21,
    velo: 87.6,
    whiff: 0.42,
    xwoba: 0.22,
    putaway: 0.36,
    locationGrid: makeGrid(8, 3, 1.7),
  },
  {
    code: "CH",
    name: "Changeup",
    usage: 0.17,
    velo: 87.1,
    whiff: 0.38,
    xwoba: 0.24,
    putaway: 0.3,
    locationGrid: makeGrid(8, 8, 1.9),
  },
];

const BURNES_MIX: PitchMixRow[] = [
  {
    code: "FC",
    name: "Cutter",
    usage: 0.55,
    velo: 95.4,
    whiff: 0.26,
    xwoba: 0.28,
    putaway: 0.23,
    locationGrid: makeGrid(5, 4, 1.7),
  },
  {
    code: "CB",
    name: "Curveball",
    usage: 0.21,
    velo: 80.2,
    whiff: 0.31,
    xwoba: 0.25,
    putaway: 0.27,
    locationGrid: makeGrid(9, 4, 2.0),
  },
  {
    code: "SL",
    name: "Slider",
    usage: 0.14,
    velo: 86.5,
    whiff: 0.35,
    xwoba: 0.27,
    putaway: 0.3,
    locationGrid: makeGrid(8, 3, 1.7),
  },
  {
    code: "CH",
    name: "Changeup",
    usage: 0.1,
    velo: 87.8,
    whiff: 0.31,
    xwoba: 0.29,
    putaway: 0.22,
    locationGrid: makeGrid(8, 8, 2.0),
  },
];

const STRIDER_MIX: PitchMixRow[] = [
  {
    code: "FF",
    name: "Four-seam",
    usage: 0.62,
    velo: 98.4,
    whiff: 0.33,
    xwoba: 0.28,
    putaway: 0.28,
    locationGrid: makeGrid(2, 5, 1.7),
  },
  {
    code: "SL",
    name: "Slider",
    usage: 0.31,
    velo: 84.2,
    whiff: 0.46,
    xwoba: 0.21,
    putaway: 0.38,
    locationGrid: makeGrid(9, 3, 1.6),
  },
  {
    code: "CH",
    name: "Changeup",
    usage: 0.07,
    velo: 87.6,
    whiff: 0.29,
    xwoba: 0.31,
    putaway: 0.2,
    locationGrid: makeGrid(8, 8, 2.1),
  },
];

const PITCHER_MIX: Record<string, PitchMixRow[]> = {
  skubal_tarik: SKUBAL_MIX,
  cole_gerrit: COLE_MIX,
  skenes_paul: SKENES_MIX,
  burnes_corbin: BURNES_MIX,
  strider_spencer: STRIDER_MIX,
};

// ── Batter splits + spray ────────────────────────────────────────────────────

const JUDGE_SPLITS: SplitRow[] = [
  {
    split: "vs LHP",
    pa: 184,
    avg: 0.302,
    obp: 0.421,
    slg: 0.687,
    iso: 0.385,
    xwoba: 0.452,
    k: 0.226,
    bb: 0.158,
  },
  {
    split: "vs RHP",
    pa: 423,
    avg: 0.276,
    obp: 0.388,
    slg: 0.572,
    iso: 0.296,
    xwoba: 0.401,
    k: 0.281,
    bb: 0.141,
  },
  {
    split: "Bases empty",
    pa: 312,
    avg: 0.281,
    obp: 0.392,
    slg: 0.598,
    iso: 0.317,
    xwoba: 0.41,
    k: 0.262,
    bb: 0.143,
  },
  {
    split: "RISP",
    pa: 174,
    avg: 0.295,
    obp: 0.414,
    slg: 0.624,
    iso: 0.329,
    xwoba: 0.432,
    k: 0.241,
    bb: 0.165,
  },
  {
    split: "2-strike",
    pa: 295,
    avg: 0.198,
    obp: 0.301,
    slg: 0.382,
    iso: 0.184,
    xwoba: 0.302,
    k: 0.392,
    bb: 0.116,
  },
];

const TROUT_SPLITS: SplitRow[] = [
  {
    split: "vs LHP",
    pa: 152,
    avg: 0.298,
    obp: 0.413,
    slg: 0.642,
    iso: 0.344,
    xwoba: 0.438,
    k: 0.218,
    bb: 0.154,
  },
  {
    split: "vs RHP",
    pa: 387,
    avg: 0.269,
    obp: 0.371,
    slg: 0.521,
    iso: 0.252,
    xwoba: 0.379,
    k: 0.268,
    bb: 0.131,
  },
  {
    split: "Bases empty",
    pa: 286,
    avg: 0.275,
    obp: 0.385,
    slg: 0.548,
    iso: 0.273,
    xwoba: 0.392,
    k: 0.254,
    bb: 0.138,
  },
  {
    split: "RISP",
    pa: 168,
    avg: 0.288,
    obp: 0.399,
    slg: 0.578,
    iso: 0.29,
    xwoba: 0.418,
    k: 0.232,
    bb: 0.152,
  },
  {
    split: "2-strike",
    pa: 274,
    avg: 0.187,
    obp: 0.289,
    slg: 0.342,
    iso: 0.155,
    xwoba: 0.28,
    k: 0.381,
    bb: 0.106,
  },
];

const SOTO_SPLITS: SplitRow[] = [
  {
    split: "vs LHP",
    pa: 198,
    avg: 0.281,
    obp: 0.408,
    slg: 0.521,
    iso: 0.24,
    xwoba: 0.405,
    k: 0.182,
    bb: 0.18,
  },
  {
    split: "vs RHP",
    pa: 456,
    avg: 0.301,
    obp: 0.452,
    slg: 0.602,
    iso: 0.301,
    xwoba: 0.439,
    k: 0.158,
    bb: 0.204,
  },
  {
    split: "Bases empty",
    pa: 338,
    avg: 0.298,
    obp: 0.44,
    slg: 0.581,
    iso: 0.283,
    xwoba: 0.423,
    k: 0.169,
    bb: 0.196,
  },
  {
    split: "RISP",
    pa: 192,
    avg: 0.291,
    obp: 0.434,
    slg: 0.564,
    iso: 0.273,
    xwoba: 0.414,
    k: 0.176,
    bb: 0.198,
  },
  {
    split: "2-strike",
    pa: 318,
    avg: 0.218,
    obp: 0.342,
    slg: 0.378,
    iso: 0.16,
    xwoba: 0.31,
    k: 0.298,
    bb: 0.146,
  },
];

const OHTANI_SPLITS: SplitRow[] = [
  {
    split: "vs LHP",
    pa: 162,
    avg: 0.252,
    obp: 0.341,
    slg: 0.482,
    iso: 0.23,
    xwoba: 0.354,
    k: 0.296,
    bb: 0.116,
  },
  {
    split: "vs RHP",
    pa: 458,
    avg: 0.291,
    obp: 0.398,
    slg: 0.612,
    iso: 0.321,
    xwoba: 0.415,
    k: 0.241,
    bb: 0.146,
  },
  {
    split: "Bases empty",
    pa: 322,
    avg: 0.281,
    obp: 0.387,
    slg: 0.578,
    iso: 0.297,
    xwoba: 0.397,
    k: 0.258,
    bb: 0.138,
  },
  {
    split: "RISP",
    pa: 182,
    avg: 0.298,
    obp: 0.404,
    slg: 0.604,
    iso: 0.306,
    xwoba: 0.418,
    k: 0.232,
    bb: 0.146,
  },
  {
    split: "2-strike",
    pa: 298,
    avg: 0.198,
    obp: 0.298,
    slg: 0.384,
    iso: 0.186,
    xwoba: 0.292,
    k: 0.412,
    bb: 0.108,
  },
];

const BICHETTE_SPLITS: SplitRow[] = [
  {
    split: "vs LHP",
    pa: 168,
    avg: 0.291,
    obp: 0.342,
    slg: 0.498,
    iso: 0.207,
    xwoba: 0.358,
    k: 0.193,
    bb: 0.07,
  },
  {
    split: "vs RHP",
    pa: 412,
    avg: 0.268,
    obp: 0.318,
    slg: 0.452,
    iso: 0.184,
    xwoba: 0.328,
    k: 0.226,
    bb: 0.062,
  },
  {
    split: "Bases empty",
    pa: 308,
    avg: 0.274,
    obp: 0.324,
    slg: 0.466,
    iso: 0.192,
    xwoba: 0.336,
    k: 0.218,
    bb: 0.064,
  },
  {
    split: "RISP",
    pa: 178,
    avg: 0.284,
    obp: 0.336,
    slg: 0.482,
    iso: 0.198,
    xwoba: 0.346,
    k: 0.211,
    bb: 0.068,
  },
  {
    split: "2-strike",
    pa: 284,
    avg: 0.182,
    obp: 0.221,
    slg: 0.282,
    iso: 0.1,
    xwoba: 0.234,
    k: 0.341,
    bb: 0.046,
  },
];

const BATTER_SPLITS: Record<string, SplitRow[]> = {
  judge_aaron: JUDGE_SPLITS,
  trout_mike: TROUT_SPLITS,
  soto_juan: SOTO_SPLITS,
  ohtani_shohei: OHTANI_SPLITS,
  bichette_bo: BICHETTE_SPLITS,
};

/** Pull-skewed spray for Judge (RHB pull = LF). */
const JUDGE_SPRAY: SprayZone[] = [
  { id: "LF-pull", label: "LF pull", count: 142, density: 0.92 },
  { id: "LF-gap", label: "LF gap", count: 96, density: 0.74 },
  { id: "CF", label: "CF", count: 71, density: 0.52 },
  { id: "RF-gap", label: "RF gap", count: 38, density: 0.3 },
  { id: "RF-oppo", label: "RF oppo", count: 22, density: 0.18 },
];

const TROUT_SPRAY: SprayZone[] = [
  { id: "LF-pull", label: "LF pull", count: 118, density: 0.78 },
  { id: "LF-gap", label: "LF gap", count: 104, density: 0.71 },
  { id: "CF", label: "CF", count: 88, density: 0.62 },
  { id: "RF-gap", label: "RF gap", count: 54, density: 0.42 },
  { id: "RF-oppo", label: "RF oppo", count: 31, density: 0.25 },
];

/** Pull-skewed for an LHB (Soto pull = RF). */
const SOTO_SPRAY: SprayZone[] = [
  { id: "LF-oppo", label: "LF oppo", count: 24, density: 0.2 },
  { id: "LF-gap", label: "LF gap", count: 42, density: 0.34 },
  { id: "CF", label: "CF", count: 79, density: 0.58 },
  { id: "RF-gap", label: "RF gap", count: 108, density: 0.78 },
  { id: "RF-pull", label: "RF pull", count: 132, density: 0.9 },
];

const OHTANI_SPRAY: SprayZone[] = [
  { id: "LF-oppo", label: "LF oppo", count: 28, density: 0.23 },
  { id: "LF-gap", label: "LF gap", count: 48, density: 0.38 },
  { id: "CF", label: "CF", count: 76, density: 0.55 },
  { id: "RF-gap", label: "RF gap", count: 112, density: 0.82 },
  { id: "RF-pull", label: "RF pull", count: 128, density: 0.92 },
];

const BICHETTE_SPRAY: SprayZone[] = [
  { id: "LF-pull", label: "LF pull", count: 96, density: 0.7 },
  { id: "LF-gap", label: "LF gap", count: 104, density: 0.75 },
  { id: "CF", label: "CF", count: 102, density: 0.74 },
  { id: "RF-gap", label: "RF gap", count: 76, density: 0.56 },
  { id: "RF-oppo", label: "RF oppo", count: 48, density: 0.38 },
];

const BATTER_SPRAY: Record<string, SprayZone[]> = {
  judge_aaron: JUDGE_SPRAY,
  trout_mike: TROUT_SPRAY,
  soto_juan: SOTO_SPRAY,
  ohtani_shohei: OHTANI_SPRAY,
  bichette_bo: BICHETTE_SPRAY,
};

// ── Recent predictions ───────────────────────────────────────────────────────

const RECENT_JUDGE_SKUBAL: MatchupPrediction[] = [
  {
    when: "2026-05-22T19:14",
    predicted: "K-swinging",
    prob: 0.34,
    actual: "K-swinging",
    agreed: true,
  },
  {
    when: "2026-05-22T19:18",
    predicted: "Foul",
    prob: 0.29,
    actual: "Foul",
    agreed: true,
  },
  {
    when: "2026-05-22T19:23",
    predicted: "Single",
    prob: 0.21,
    actual: "HR",
    agreed: false,
  },
  {
    when: "2026-05-22T20:01",
    predicted: "Whiff",
    prob: 0.41,
    actual: "Whiff",
    agreed: true,
  },
  {
    when: "2026-05-22T20:09",
    predicted: "Ball",
    prob: 0.38,
    actual: "Called strike",
    agreed: false,
  },
  {
    when: "2026-05-22T20:14",
    predicted: "Fly out",
    prob: 0.27,
    actual: "Fly out",
    agreed: true,
  },
  {
    when: "2026-05-12T18:42",
    predicted: "K-looking",
    prob: 0.31,
    actual: "K-looking",
    agreed: true,
  },
  {
    when: "2026-05-12T19:11",
    predicted: "Walk",
    prob: 0.28,
    actual: "Walk",
    agreed: true,
  },
  {
    when: "2026-05-12T19:38",
    predicted: "Double",
    prob: 0.18,
    actual: "K-swinging",
    agreed: false,
  },
  {
    when: "2026-04-29T22:04",
    predicted: "Foul",
    prob: 0.32,
    actual: "Foul",
    agreed: true,
  },
  {
    when: "2026-04-29T22:11",
    predicted: "Whiff",
    prob: 0.39,
    actual: "Whiff",
    agreed: true,
  },
  {
    when: "2026-04-29T22:19",
    predicted: "Single",
    prob: 0.24,
    actual: "Single",
    agreed: true,
  },
];

// Used for any matchup that doesn't have hand-tailored predictions.
const GENERIC_RECENT: MatchupPrediction[] = [
  {
    when: "2026-05-20T19:32",
    predicted: "Foul",
    prob: 0.29,
    actual: "Foul",
    agreed: true,
  },
  {
    when: "2026-05-20T19:38",
    predicted: "Ball",
    prob: 0.34,
    actual: "Ball",
    agreed: true,
  },
  {
    when: "2026-05-20T19:44",
    predicted: "K-swinging",
    prob: 0.32,
    actual: "Single",
    agreed: false,
  },
  {
    when: "2026-05-20T20:11",
    predicted: "Whiff",
    prob: 0.41,
    actual: "Whiff",
    agreed: true,
  },
  {
    when: "2026-05-20T20:17",
    predicted: "Fly out",
    prob: 0.26,
    actual: "Fly out",
    agreed: true,
  },
  {
    when: "2026-05-13T18:18",
    predicted: "Walk",
    prob: 0.31,
    actual: "Walk",
    agreed: true,
  },
  {
    when: "2026-05-13T18:32",
    predicted: "Single",
    prob: 0.22,
    actual: "Double",
    agreed: false,
  },
  {
    when: "2026-05-13T19:06",
    predicted: "K-looking",
    prob: 0.28,
    actual: "K-looking",
    agreed: true,
  },
  {
    when: "2026-05-04T20:42",
    predicted: "Foul",
    prob: 0.3,
    actual: "Foul",
    agreed: true,
  },
  {
    when: "2026-05-04T20:51",
    predicted: "Whiff",
    prob: 0.38,
    actual: "Whiff",
    agreed: true,
  },
  {
    when: "2026-05-04T20:58",
    predicted: "Single",
    prob: 0.23,
    actual: "Single",
    agreed: true,
  },
  {
    when: "2026-05-04T21:04",
    predicted: "Ground out",
    prob: 0.27,
    actual: "Ground out",
    agreed: true,
  },
];

// ── Calibration ──────────────────────────────────────────────────────────────

const JUDGE_CALIBRATION: CalibrationBin[] = [
  { binStart: 0.0, binEnd: 0.1, predicted: 0.05, actual: 0.06, n: 312 },
  { binStart: 0.1, binEnd: 0.2, predicted: 0.15, actual: 0.14, n: 284 },
  { binStart: 0.2, binEnd: 0.3, predicted: 0.25, actual: 0.27, n: 251 },
  { binStart: 0.3, binEnd: 0.4, predicted: 0.35, actual: 0.34, n: 198 },
  { binStart: 0.4, binEnd: 0.5, predicted: 0.45, actual: 0.43, n: 142 },
  { binStart: 0.5, binEnd: 0.6, predicted: 0.55, actual: 0.58, n: 96 },
  { binStart: 0.6, binEnd: 0.7, predicted: 0.65, actual: 0.62, n: 74 },
  { binStart: 0.7, binEnd: 0.8, predicted: 0.75, actual: 0.78, n: 52 },
  { binStart: 0.8, binEnd: 0.9, predicted: 0.85, actual: 0.83, n: 38 },
  { binStart: 0.9, binEnd: 1.0, predicted: 0.95, actual: 0.94, n: 22 },
];

// ── Pairings + lookup ────────────────────────────────────────────────────────

/**
 * Symmetric matchup graph. Keyed by either side's id — looking up `judge_aaron`
 * returns the Judge → Skubal pairing; looking up `skubal_tarik` returns the
 * same pairing with `primary` flipped.
 */
const PAIRINGS: Array<[string, string]> = [
  ["judge_aaron", "skubal_tarik"],
  ["trout_mike", "cole_gerrit"],
  ["soto_juan", "skubal_tarik"],
  ["ohtani_shohei", "cole_gerrit"],
  ["bichette_bo", "skenes_paul"],
];

function findPairing(id: string): [string, string] | null {
  for (const [a, b] of PAIRINGS) {
    if (a === id || b === id) return [a, b];
  }
  return null;
}

const KEY_NOTES_JUDGE_SKUBAL: string[] = [
  "Expect Skubal to elevate the four-seamer early — 42 % usage, 97-mph velo, 31 % whiff rate. Judge's 2-strike xwOBA collapses to .302 vs his .452 vs LHP overall, so the first-pitch heater is the at-bat.",
  "Slider is the put-away pitch — low-arm-side, 41 % whiff, 33 % put-away rate. Judge's pull-side authority means a hung slider middle-in is the homer-risk corridor.",
  "Calibration on this matchup is honest (ECE ≈ 0.012, n = 1469). Probabilities above 0.45 have been mildly under-confident — read close calls in Judge's favor at the high end.",
];

const KEY_NOTES_GENERIC: string[] = [
  "Pitcher leans on the primary fastball early; secondary breaking pitch is the put-away. Watch the first-pitch zone tendency for the at-bat plan.",
  "Batter splits favor the matchup hand; pull-side authority is the dominant homer-risk corridor.",
  "Calibration on this matchup is broadly trustworthy (ECE < 0.02, n > 1k). Probabilities in the 0.30–0.55 band have been the most reliable.",
];

/** Build a MatchupReport with the requested player as `primary`. */
export function getDefaultMatchup(playerId: string | undefined): MatchupReport {
  const safeId = playerId && PLAYERS[playerId] ? playerId : "judge_aaron";
  const pairing = findPairing(safeId);
  const [batterId, pitcherId] = pairing ?? ["judge_aaron", "skubal_tarik"];
  const batter = PLAYERS[batterId];
  const pitcher = PLAYERS[pitcherId];
  const primary = safeId === pitcherId ? pitcher : batter;
  const opponent = primary.id === batter.id ? pitcher : batter;

  const isJudgeSkubal =
    (batterId === "judge_aaron" && pitcherId === "skubal_tarik") ||
    (pitcherId === "judge_aaron" && batterId === "skubal_tarik");

  return {
    primary,
    opponent,
    pitcherMix: PITCHER_MIX[pitcherId] ?? SKUBAL_MIX,
    batterSplits: BATTER_SPLITS[batterId] ?? JUDGE_SPLITS,
    spray: BATTER_SPRAY[batterId] ?? JUDGE_SPRAY,
    predictions: isJudgeSkubal ? RECENT_JUDGE_SKUBAL : GENERIC_RECENT,
    calibration: JUDGE_CALIBRATION,
    keyNotes: isJudgeSkubal ? KEY_NOTES_JUDGE_SKUBAL : KEY_NOTES_GENERIC,
    context: isJudgeSkubal
      ? "NYY @ DET · Wed May 27, 2026 · 7:10 PM ET · Comerica Park"
      : `${batter.team} vs ${pitcher.team} · 2026 season aggregate`,
  };
}
