"""Production model persistence (Phase 2a.7).

For each registered model version, writes the 5 canonical files +
eval/ directory:

    artifacts/<model_name>/<version>/
      ├── model.lgb            # LightGBM only; LR writes model.pkl
      ├── model.pkl            # LR baseline only (joblib)
      ├── calibrator.json
      ├── metadata.json        # provenance: git_commit, data_hash, train_window,
      │                          hyperparams, eval_metrics_summary
      ├── feature_pipeline.json (copied from /contracts)
      ├── training_data.parquet (test-fold snapshot for downstream eval)
      └── eval/                 (generated by bullpen_training.eval.artifact)

ONNX export lands in 2a.8 (separate module so the Java side has a
single place to look for `.onnx` files).
"""

from __future__ import annotations

import hashlib
import json
import logging
import shutil
import subprocess
from dataclasses import dataclass
from datetime import UTC, datetime
from pathlib import Path
from typing import Any

import joblib
import numpy as np
import pandas as pd

from bullpen_training.eval.artifact import (
    ArtifactInputs,
    hash_dataframe,
    lightgbm_feature_importance,
)
from bullpen_training.eval.artifact import (
    generate as generate_eval,
)
from bullpen_training.eval.cv_harness import CVResult
from bullpen_training.features import LABEL_CLASSES
from bullpen_training.pitch import PITCH_FEATURE_COLUMNS
from bullpen_training.pitch.train_lr_baseline import LRModelBundle
from bullpen_training.pitch.train_pre import ModelBundle

log = logging.getLogger(__name__)

REPO_ROOT = Path(__file__).resolve().parents[4]
DEFAULT_ARTIFACTS_DIR = REPO_ROOT / "training" / "artifacts"
CONTRACT_PATH = REPO_ROOT / "contracts" / "feature_pipeline.json"


@dataclass(frozen=True)
class PersistInputs:
    model_name: str
    model_version: str
    train_window: str
    val_window: str
    test_df: pd.DataFrame
    test_predictions: np.ndarray
    cv_result: CVResult
    hyperparams: dict[str, Any]


def _git_commit_sha() -> str:
    try:
        return subprocess.check_output(
            ["git", "rev-parse", "HEAD"], cwd=str(REPO_ROOT), text=True
        ).strip()
    except (subprocess.CalledProcessError, FileNotFoundError):
        return "unknown"


def _sha256_of_path(path: Path) -> str:
    h = hashlib.sha256()
    with path.open("rb") as fh:
        for chunk in iter(lambda: fh.read(8192), b""):
            h.update(chunk)
    return h.hexdigest()


def _write_metadata(
    out_dir: Path,
    inputs: PersistInputs,
    model_artifact_path: Path,
    *,
    training_data_hash: str,
    calibrator_path: Path,
    extras: dict[str, Any] | None = None,
) -> Path:
    payload: dict[str, Any] = {
        "model_name": inputs.model_name,
        "model_version": inputs.model_version,
        "phase": "2a",
        "training_data_window": inputs.train_window,
        "val_window": inputs.val_window,
        "training_data_hash": training_data_hash,
        "model_artifact": {
            "path": model_artifact_path.name,
            "sha256": _sha256_of_path(model_artifact_path),
        },
        "calibrator": {
            "path": calibrator_path.name,
            "sha256": _sha256_of_path(calibrator_path),
        },
        "feature_pipeline_hash": json.loads(CONTRACT_PATH.read_text())["schema_hash"],
        "git_commit": _git_commit_sha(),
        "trained_at": datetime.now(UTC).isoformat(timespec="seconds"),
        "hyperparams": inputs.hyperparams,
        "eval_metrics_summary": {
            name: {"mean": mean, "std": std}
            for name, (mean, std) in inputs.cv_result.summary.items()
        },
        "eval_metrics_per_fold": [
            {
                "fold_id": fr.fold_id,
                "train_rows": fr.train_rows,
                "val_rows": fr.val_rows,
                "test_rows": fr.test_rows,
                "metrics": fr.metrics,
            }
            for fr in inputs.cv_result.per_fold
        ],
    }
    if extras:
        payload.update(extras)
    meta_path = out_dir / "metadata.json"
    meta_path.write_text(json.dumps(payload, indent=2, sort_keys=False) + "\n")
    return meta_path


def _copy_feature_pipeline(out_dir: Path) -> None:
    shutil.copyfile(CONTRACT_PATH, out_dir / "feature_pipeline.json")


def _write_training_data_snapshot(out_dir: Path, df: pd.DataFrame) -> tuple[Path, str]:
    path = out_dir / "training_data.parquet"
    df.to_parquet(path, index=False)
    return path, hash_dataframe(df)


def persist_lightgbm_v1(
    bundle: ModelBundle,
    inputs: PersistInputs,
    *,
    artifacts_dir: Path | None = None,
) -> Path:
    """Write the 5 canonical files + eval/ for the LightGBM bundle."""
    base = artifacts_dir or DEFAULT_ARTIFACTS_DIR
    out_dir = base / inputs.model_name / inputs.model_version
    out_dir.mkdir(parents=True, exist_ok=True)

    model_path = out_dir / "model.lgb"
    bundle.booster.save_model(str(model_path))

    cal_path = out_dir / "calibrator.json"
    bundle.calibrator.to_json(cal_path)

    _copy_feature_pipeline(out_dir)

    snapshot_path, data_hash = _write_training_data_snapshot(out_dir, inputs.test_df)

    _write_metadata(
        out_dir,
        inputs,
        model_path,
        training_data_hash=data_hash,
        calibrator_path=cal_path,
    )

    fi = lightgbm_feature_importance(bundle.booster, list(PITCH_FEATURE_COLUMNS))
    generate_eval(
        ArtifactInputs(
            model_name=inputs.model_name,
            model_version=inputs.model_version,
            class_labels=list(LABEL_CLASSES),
            cv_result=inputs.cv_result,
            test_df=inputs.test_df,
            test_predictions=inputs.test_predictions,
            training_data_hash=data_hash,
            feature_importance=fi,
        ),
        out_dir,
    )

    log.info("persisted LightGBM bundle to %s (snapshot %s)", out_dir, snapshot_path)
    return out_dir


def persist_lr_baseline_v1(
    bundle: LRModelBundle,
    inputs: PersistInputs,
    *,
    artifacts_dir: Path | None = None,
) -> Path:
    """Write LR baseline files. ONNX export deferred to 2a.8."""
    base = artifacts_dir or DEFAULT_ARTIFACTS_DIR
    out_dir = base / inputs.model_name / inputs.model_version
    out_dir.mkdir(parents=True, exist_ok=True)

    model_path = out_dir / "model.pkl"
    joblib.dump(bundle.pipeline, model_path)

    cal_path = out_dir / "calibrator.json"
    bundle.calibrator.to_json(cal_path)

    _copy_feature_pipeline(out_dir)

    snapshot_path, data_hash = _write_training_data_snapshot(out_dir, inputs.test_df)

    _write_metadata(
        out_dir,
        inputs,
        model_path,
        training_data_hash=data_hash,
        calibrator_path=cal_path,
        extras={
            "fitted_label_classes": list(bundle.fitted_label_classes),
        },
    )

    # LR has no comparable feature_importance.csv — coefficients aren't on
    # the same scale as LightGBM gain. Skip per leaf 2a.7.
    generate_eval(
        ArtifactInputs(
            model_name=inputs.model_name,
            model_version=inputs.model_version,
            class_labels=list(LABEL_CLASSES),
            cv_result=inputs.cv_result,
            test_df=inputs.test_df,
            test_predictions=inputs.test_predictions,
            training_data_hash=data_hash,
            feature_importance=None,
        ),
        out_dir,
    )

    log.info("persisted LR baseline bundle to %s (snapshot %s)", out_dir, snapshot_path)
    return out_dir
