"""Production model persistence (Phase 2a.7 + 2a.8).

For each registered model version, writes the canonical files +
eval/ directory. As of 2a.8, also drops the Tier 1+2 lookup tables the
Java serving path needs to reproduce the Python feature pipeline
bit-for-bit (CLAUDE.md rule 7 — feature schema hash is enforced).

    artifacts/<model_name>/<version>/
      ├── model.lgb            # LightGBM only; LR writes model.pkl
      ├── model.pkl            # LR baseline only (joblib)
      ├── model.onnx           # LightGBM only; written by 2a.8 export step
      ├── calibrator.json
      ├── metadata.json        # provenance: git_commit, data_hash, train_window,
      │                          hyperparams, eval_metrics_summary
      ├── feature_pipeline.json   (copied from /contracts)
      ├── park_id_mapping.json    (2a.8 — loader's deterministic park→int)
      ├── pitcher_te.json         (2a.8 — copied from artifacts/encodings/pitcher_fold{N}.json)
      ├── batter_te.json          (2a.8 — copied from artifacts/encodings/batter_fold{N}.json)
      ├── training_data.parquet (test-fold snapshot for downstream eval)
      └── eval/                 (generated by bullpen_training.eval.artifact)
"""

from __future__ import annotations

import hashlib
import json
import logging
import shutil
import subprocess
from dataclasses import dataclass
from datetime import UTC, datetime
from pathlib import Path
from typing import Any

import joblib
import numpy as np
import pandas as pd

from bullpen_training.eval.artifact import (
    ArtifactInputs,
    hash_dataframe,
    lightgbm_feature_importance,
)
from bullpen_training.eval.artifact import (
    generate as generate_eval,
)
from bullpen_training.eval.cv_harness import CVResult
from bullpen_training.features import LABEL_CLASSES
from bullpen_training.pitch.train_lr_baseline import LRModelBundle
from bullpen_training.pitch.train_pre import ModelBundle

log = logging.getLogger(__name__)

REPO_ROOT = Path(__file__).resolve().parents[4]
DEFAULT_ARTIFACTS_DIR = REPO_ROOT / "training" / "artifacts"
CONTRACT_PATH = REPO_ROOT / "contracts" / "feature_pipeline.json"
ENCODINGS_DIR = DEFAULT_ARTIFACTS_DIR / "encodings"


@dataclass(frozen=True)
class PersistInputs:
    model_name: str
    model_version: str
    train_window: str
    val_window: str
    test_df: pd.DataFrame
    test_predictions: np.ndarray
    cv_result: CVResult
    hyperparams: dict[str, Any]
    # 2a.8 additions — Java-side lookups so feature pipeline reproduces in serving.
    fold_id: int = 4
    park_id_mapping: dict[str, int] | None = None
    pitcher_te_path: Path | None = None
    batter_te_path: Path | None = None


def _git_commit_sha() -> str:
    try:
        return subprocess.check_output(
            ["git", "rev-parse", "HEAD"], cwd=str(REPO_ROOT), text=True
        ).strip()
    except (subprocess.CalledProcessError, FileNotFoundError):
        return "unknown"


def _sha256_of_path(path: Path) -> str:
    h = hashlib.sha256()
    with path.open("rb") as fh:
        for chunk in iter(lambda: fh.read(8192), b""):
            h.update(chunk)
    return h.hexdigest()


def _write_metadata(
    out_dir: Path,
    inputs: PersistInputs,
    model_artifact_path: Path,
    *,
    training_data_hash: str,
    calibrator_path: Path,
    extras: dict[str, Any] | None = None,
) -> Path:
    payload: dict[str, Any] = {
        "model_name": inputs.model_name,
        "model_version": inputs.model_version,
        "phase": "2a",
        "training_data_window": inputs.train_window,
        "val_window": inputs.val_window,
        "training_data_hash": training_data_hash,
        "model_artifact": {
            "path": model_artifact_path.name,
            "sha256": _sha256_of_path(model_artifact_path),
        },
        "calibrator": {
            "path": calibrator_path.name,
            "sha256": _sha256_of_path(calibrator_path),
        },
        "feature_pipeline_hash": json.loads(CONTRACT_PATH.read_text())["schema_hash"],
        "git_commit": _git_commit_sha(),
        "trained_at": datetime.now(UTC).isoformat(timespec="seconds"),
        "hyperparams": inputs.hyperparams,
        "eval_metrics_summary": {
            name: {"mean": mean, "std": std}
            for name, (mean, std) in inputs.cv_result.summary.items()
        },
        "eval_metrics_per_fold": [
            {
                "fold_id": fr.fold_id,
                "train_rows": fr.train_rows,
                "val_rows": fr.val_rows,
                "test_rows": fr.test_rows,
                "metrics": fr.metrics,
            }
            for fr in inputs.cv_result.per_fold
        ],
    }
    if extras:
        payload.update(extras)
    meta_path = out_dir / "metadata.json"
    meta_path.write_text(json.dumps(payload, indent=2, sort_keys=False) + "\n")
    return meta_path


def _copy_feature_pipeline(out_dir: Path) -> None:
    shutil.copyfile(CONTRACT_PATH, out_dir / "feature_pipeline.json")


def _write_park_id_mapping(out_dir: Path, mapping: dict[str, int]) -> Path:
    """Persist the loader's park_id → int mapping for Java consumption.

    Format mirrors the deterministic-JSON shape used by the TE encodings:
    sorted by key for byte-stability, indented for human inspection.
    """
    payload = {"park_id": dict(sorted(mapping.items())), "missing_value": -1}
    path = out_dir / "park_id_mapping.json"
    path.write_text(json.dumps(payload, indent=2, sort_keys=False) + "\n")
    return path


def _copy_te_lookup(src: Path, dest: Path) -> Path:
    """Copy a TE lookup JSON into the model dir under the canonical name."""
    if not src.exists():
        raise FileNotFoundError(
            f"TE lookup not found at {src}; run "
            "bullpen_training.features.build_features for the matching fold first"
        )
    shutil.copyfile(src, dest)
    return dest


def _write_lookups_for_pipeline(out_dir: Path, inputs: PersistInputs) -> None:
    """Write the three Java-side lookups derived from the loader's fold:

    - ``park_id_mapping.json`` — deterministic park_id → int (in inputs)
    - ``pitcher_te.json``      — copied from ``artifacts/encodings/pitcher_fold{N}.json``
    - ``batter_te.json``       — copied from ``artifacts/encodings/batter_fold{N}.json``

    Skips writing each file when its source isn't provided — callers
    that don't need pipe-Java parity (LR smoke; unit tests) can opt
    out by leaving the inputs fields ``None``.
    """
    if inputs.park_id_mapping is not None:
        _write_park_id_mapping(out_dir, inputs.park_id_mapping)
    pitcher_src = inputs.pitcher_te_path or (ENCODINGS_DIR / f"pitcher_fold{inputs.fold_id}.json")
    if pitcher_src.exists():
        _copy_te_lookup(pitcher_src, out_dir / "pitcher_te.json")
    batter_src = inputs.batter_te_path or (ENCODINGS_DIR / f"batter_fold{inputs.fold_id}.json")
    if batter_src.exists():
        _copy_te_lookup(batter_src, out_dir / "batter_te.json")


def _write_training_data_snapshot(out_dir: Path, df: pd.DataFrame) -> tuple[Path, str]:
    path = out_dir / "training_data.parquet"
    df.to_parquet(path, index=False)
    return path, hash_dataframe(df)


def persist_lightgbm_v1(
    bundle: ModelBundle,
    inputs: PersistInputs,
    *,
    artifacts_dir: Path | None = None,
) -> Path:
    """Write the canonical files + eval/ for the LightGBM bundle."""
    base = artifacts_dir or DEFAULT_ARTIFACTS_DIR
    out_dir = base / inputs.model_name / inputs.model_version
    out_dir.mkdir(parents=True, exist_ok=True)

    model_path = out_dir / "model.lgb"
    bundle.booster.save_model(str(model_path))

    cal_path = out_dir / "calibrator.json"
    bundle.calibrator.to_json(cal_path)

    _copy_feature_pipeline(out_dir)
    _write_lookups_for_pipeline(out_dir, inputs)

    snapshot_path, data_hash = _write_training_data_snapshot(out_dir, inputs.test_df)

    _write_metadata(
        out_dir,
        inputs,
        model_path,
        training_data_hash=data_hash,
        calibrator_path=cal_path,
    )

    # bundle.feature_cols carries the actual training feature order — pre uses
    # PITCH_FEATURE_COLUMNS (31), post uses PITCH_FEATURE_COLUMNS_POST (41).
    # Hardcoding PITCH_FEATURE_COLUMNS would crash persist on the post head
    # (booster.feature_importance() returns 41 values, names list has 31).
    fi = lightgbm_feature_importance(bundle.booster, list(bundle.feature_cols))
    generate_eval(
        ArtifactInputs(
            model_name=inputs.model_name,
            model_version=inputs.model_version,
            class_labels=list(LABEL_CLASSES),
            cv_result=inputs.cv_result,
            test_df=inputs.test_df,
            test_predictions=inputs.test_predictions,
            training_data_hash=data_hash,
            feature_importance=fi,
        ),
        out_dir,
    )

    log.info("persisted LightGBM bundle to %s (snapshot %s)", out_dir, snapshot_path)
    return out_dir


def persist_lr_baseline_v1(
    bundle: LRModelBundle,
    inputs: PersistInputs,
    *,
    artifacts_dir: Path | None = None,
) -> Path:
    """Write LR baseline files. LR has no ONNX export (sklearn pipeline)."""
    base = artifacts_dir or DEFAULT_ARTIFACTS_DIR
    out_dir = base / inputs.model_name / inputs.model_version
    out_dir.mkdir(parents=True, exist_ok=True)

    model_path = out_dir / "model.pkl"
    joblib.dump(bundle.pipeline, model_path)

    cal_path = out_dir / "calibrator.json"
    bundle.calibrator.to_json(cal_path)

    _copy_feature_pipeline(out_dir)
    _write_lookups_for_pipeline(out_dir, inputs)

    snapshot_path, data_hash = _write_training_data_snapshot(out_dir, inputs.test_df)

    _write_metadata(
        out_dir,
        inputs,
        model_path,
        training_data_hash=data_hash,
        calibrator_path=cal_path,
        extras={
            "fitted_label_classes": list(bundle.fitted_label_classes),
        },
    )

    # LR has no comparable feature_importance.csv — coefficients aren't on
    # the same scale as LightGBM gain. Skip per leaf 2a.7.
    generate_eval(
        ArtifactInputs(
            model_name=inputs.model_name,
            model_version=inputs.model_version,
            class_labels=list(LABEL_CLASSES),
            cv_result=inputs.cv_result,
            test_df=inputs.test_df,
            test_predictions=inputs.test_predictions,
            training_data_hash=data_hash,
            feature_importance=None,
        ),
        out_dir,
    )

    log.info("persisted LR baseline bundle to %s (snapshot %s)", out_dir, snapshot_path)
    return out_dir
