package net.thebullpen.baseball.inference;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertTrue;

import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.List;
import java.util.Map;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.condition.EnabledIf;

/**
 * Java side of the Python<->Java parity contract for the batted-ball per-park OUTCOME model (B5,
 * decision [146]).
 *
 * <p>Reads {@code parity_battedball_allparks_001*.json} (generated by {@code
 * bullpen_training.battedball.mlp.parity_fixture_allparks}) and runs each row through the EXACT
 * serving path:
 *
 * <ol>
 *   <li>{@link FeaturePipelineBattedBall} (7 inputs -> 15-feature float vector, z-scored)
 *   <li>{@link BattedBallOnnxModel} ({@code [None,15] -> [None,30,5]} per-park softmax)
 *   <li>{@link BattedBallCalibrators} (per-park isotonic + renormalize)
 * </ol>
 *
 * <p>and asserts the 15-feature vector and the calibrated per-park distribution match the fixture
 * within its declared tolerance. Drift here means the Java serving has silently diverged from the
 * Python exporter - the [148] softmax-baked-into-export contract and the [146] calibrated-serving
 * chain are closed end-to-end only while this stays green.
 *
 * <p>Self-disables when the fixture + the registered model artifacts are absent (a fresh clone / CI
 * without the trained model), exactly like {@code PitchPreParityTest}; it runs on the desktop (or
 * locally once {@code make sync-mirror} has pulled the snapshot) where the artifacts live.
 */
class BattedBallAllParksParityTest {

  private static final Path REPO_ROOT = Path.of(System.getProperty("user.dir")).getParent();
  private static final Path FIXTURE_DIR = REPO_ROOT.resolve("training/tests/fixtures");
  private static final Path INPUT_PATH = FIXTURE_DIR.resolve("parity_battedball_allparks_001.json");
  private static final Path EXPECTED_PATH =
      FIXTURE_DIR.resolve("parity_battedball_allparks_001_expected.json");
  private static final Path ARTIFACT_DIR =
      REPO_ROOT.resolve("training/artifacts/battedball_outcome/v1");
  private static final Path ONNX_PATH = ARTIFACT_DIR.resolve("model.onnx");
  private static final Path METADATA_PATH = ARTIFACT_DIR.resolve("metadata.json");
  private static final Path CALIBRATOR_PATH = ARTIFACT_DIR.resolve("calibrator.json");
  private static final Path CONTRACT_PATH =
      REPO_ROOT.resolve("contracts/feature_pipeline_battedball.json");

  @SuppressWarnings("unused")
  static boolean fixtureAndArtifactsPresent() {
    return Files.exists(INPUT_PATH)
        && Files.exists(EXPECTED_PATH)
        && Files.exists(ONNX_PATH)
        && Files.exists(METADATA_PATH)
        && Files.exists(CALIBRATOR_PATH)
        && Files.exists(CONTRACT_PATH);
  }

  @Test
  @EnabledIf("fixtureAndArtifactsPresent")
  void schemaHashesMatchBetweenInputAndExpected() throws IOException {
    ObjectMapper mapper = new ObjectMapper();
    JsonNode input = mapper.readTree(Files.readAllBytes(INPUT_PATH));
    JsonNode expected = mapper.readTree(Files.readAllBytes(EXPECTED_PATH));
    assertEquals(
        input.get("schema_hash").asText(),
        expected.get("schema_hash").asText(),
        "input + expected fixtures came from different schema versions");
  }

  @Test
  @EnabledIf("fixtureAndArtifactsPresent")
  void javaServingMatchesPythonExporterForEveryRow() throws Exception {
    ObjectMapper mapper = new ObjectMapper();
    JsonNode input = mapper.readTree(Files.readAllBytes(INPUT_PATH));
    JsonNode expected = mapper.readTree(Files.readAllBytes(EXPECTED_PATH));
    double tolerance = expected.get("tolerance").asDouble();

    FeaturePipelineBattedBall pipeline =
        FeaturePipelineBattedBall.load(CONTRACT_PATH, METADATA_PATH);
    BattedBallCalibrators calibrators = BattedBallCalibrators.load(CALIBRATOR_PATH);
    BattedBallOnnxModel onnx = new BattedBallOnnxModel(ONNX_PATH);
    // model owns onnx; closing it closes the ORT session (so onnx isn't separately try-managed).
    try (LoadedAllParksModel model =
        new LoadedAllParksModel(
            1L,
            "battedball_outcome",
            "v1",
            expected.get("schema_hash").asText(),
            pipeline,
            onnx,
            calibrators)) {

      List<String> parkOrder = jsonStrings(expected.get("park_order"));
      assertEquals(
          parkOrder, model.parkOrder(), "fixture park_order != model (calibrator) park_order");

      JsonNode rows = input.get("rows");
      JsonNode expectedRows = expected.get("rows");
      assertEquals(rows.size(), expectedRows.size(), "input/expected row count mismatch");

      for (int i = 0; i < rows.size(); i++) {
        JsonNode raw = rows.get(i);
        JsonNode want = expectedRows.get(i);
        FeaturePipelineBattedBall.Request req = parseRequest(raw);

        // Stage 1: the 15-feature vector (catches feature-transform / scaler drift).
        float[] vector = pipeline.transform(req);
        assertVectorMatches(vector, want.get("feature_vector"), tolerance, "feature_vector", i);

        // Stage 2: the served calibrated per-park distribution (the headline parity).
        Map<String, float[]> got = model.predict(req);
        JsonNode wantCalibrated = want.get("calibrated");
        for (int p = 0; p < parkOrder.size(); p++) {
          assertVectorMatches(
              got.get(parkOrder.get(p)),
              wantCalibrated.get(p),
              tolerance,
              "calibrated[" + parkOrder.get(p) + "]",
              i);
        }
      }
    }
  }

  private static FeaturePipelineBattedBall.Request parseRequest(JsonNode raw) {
    return new FeaturePipelineBattedBall.Request(
        raw.get("launch_speed_mph").asDouble(),
        raw.get("launch_angle_deg").asDouble(),
        raw.get("spray_angle_deg").asDouble(),
        raw.get("hit_distance_ft").asDouble(),
        raw.get("stand").asText("R"),
        raw.get("base_state").asInt(),
        raw.get("outs").asInt());
  }

  private static List<String> jsonStrings(JsonNode arr) {
    return java.util.stream.StreamSupport.stream(arr.spliterator(), false)
        .map(JsonNode::asText)
        .toList();
  }

  private static void assertVectorMatches(
      float[] actual, JsonNode expected, double tolerance, String stage, int row) {
    assertEquals(expected.size(), actual.length, stage + " length mismatch on row " + row);
    for (int i = 0; i < actual.length; i++) {
      double drift = Math.abs(actual[i] - expected.get(i).asDouble());
      assertTrue(
          drift < tolerance,
          String.format(
              "%s[%d] drift %.3g > %.3g on row %d: got %f wanted %f",
              stage, i, drift, tolerance, row, actual[i], expected.get(i).asDouble()));
    }
  }
}
