package net.thebullpen.baseball.inference;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.junit.jupiter.api.Assertions.assertTrue;

import ai.onnxruntime.OnnxTensor;
import ai.onnxruntime.OrtEnvironment;
import ai.onnxruntime.OrtSession;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.Map;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.condition.EnabledIf;

/**
 * Java side of the Python↔Java parity contract for pitch_outcome_pre (Phase 2a.8).
 *
 * <p>Reads the fixture {@code parity_pitch_pre_001*.json} generated by {@code
 * bullpen_training.pitch.parity_fixture}, runs each row through:
 *
 * <ol>
 *   <li>{@link FeaturePipelinePitchPre} (Tier 1+2+3 → float32 vector)
 *   <li>ONNX Runtime ({@code model.onnx})
 *   <li>{@link IsotonicCalibratorJava}
 * </ol>
 *
 * <p>and asserts each output stage matches the fixture's expected values within {@code 1e-6}. Drift
 * here means the Java preprocess + serving path has silently diverged from Python — Risk Register
 * G1 is closed end-to-end if this stays green.
 *
 * <p>Self-disables when fixture + artifacts are missing so {@code ./gradlew test} stays green on a
 * fresh clone before the Python training has been run.
 */
class PitchPreParityTest {

  private static final Path REPO_ROOT = Path.of(System.getProperty("user.dir")).getParent();
  private static final Path FIXTURE_DIR = REPO_ROOT.resolve("training/tests/fixtures");
  private static final Path INPUT_PATH = FIXTURE_DIR.resolve("parity_pitch_pre_001.json");
  private static final Path EXPECTED_PATH =
      FIXTURE_DIR.resolve("parity_pitch_pre_001_expected.json");
  // PRE artifact version this fixture set was generated against. v1 and v2 share one feature
  // schema_hash (the clean-feature retrain changed model weights, not the feature contract), so a
  // version bump is a single edit here in lockstep with a regenerated fixture - the expected ONNX
  // raw + calibrated probabilities in the fixture are what actually pin the version.
  private static final String PRE_VERSION = "v2";
  private static final Path ARTIFACT_DIR =
      REPO_ROOT.resolve("training/artifacts/pitch_outcome_pre/" + PRE_VERSION);
  private static final Path ONNX_PATH = ARTIFACT_DIR.resolve("model.onnx");
  private static final Path CALIBRATOR_PATH = ARTIFACT_DIR.resolve("calibrator.json");
  private static final Path CONTRACT_PATH = REPO_ROOT.resolve("contracts/feature_pipeline.json");

  @SuppressWarnings("unused")
  static boolean fixtureAndArtifactsPresent() {
    return Files.exists(INPUT_PATH)
        && Files.exists(EXPECTED_PATH)
        && Files.exists(ONNX_PATH)
        && Files.exists(CALIBRATOR_PATH)
        && Files.exists(CONTRACT_PATH)
        && Files.exists(ARTIFACT_DIR.resolve("park_id_mapping.json"))
        && Files.exists(ARTIFACT_DIR.resolve("pitcher_te.json"))
        && Files.exists(ARTIFACT_DIR.resolve("batter_te.json"));
  }

  @Test
  @EnabledIf("fixtureAndArtifactsPresent")
  void schemaHashesMatchBetweenInputAndExpected() throws IOException {
    ObjectMapper mapper = new ObjectMapper();
    JsonNode input = mapper.readTree(Files.readAllBytes(INPUT_PATH));
    JsonNode expected = mapper.readTree(Files.readAllBytes(EXPECTED_PATH));
    assertEquals(
        input.get("schema_hash").asText(),
        expected.get("schema_hash").asText(),
        "input + expected fixtures came from different schema versions");
  }

  @Test
  @EnabledIf("fixtureAndArtifactsPresent")
  void javaPipelineMatchesExpectedForEveryRow() throws Exception {
    ObjectMapper mapper = new ObjectMapper();
    JsonNode input = mapper.readTree(Files.readAllBytes(INPUT_PATH));
    JsonNode expected = mapper.readTree(Files.readAllBytes(EXPECTED_PATH));
    double tolerance = expected.get("tolerance").asDouble();

    FeaturePipelinePitchPre pipeline = FeaturePipelinePitchPre.load(CONTRACT_PATH, ARTIFACT_DIR);
    IsotonicCalibratorJava calibrator = IsotonicCalibratorJava.load(CALIBRATOR_PATH);

    OrtEnvironment env = OrtEnvironment.getEnvironment();
    try (OrtSession session =
        env.createSession(ONNX_PATH.toString(), new OrtSession.SessionOptions())) {
      JsonNode rows = input.get("rows");
      JsonNode expectedRows = expected.get("rows");
      assertEquals(rows.size(), expectedRows.size(), "input/expected row count mismatch");

      for (int i = 0; i < rows.size(); i++) {
        JsonNode raw = rows.get(i);
        JsonNode want = expectedRows.get(i);

        FeaturePipelinePitchPre.Request req = parseRequest(raw);
        float[] vector = pipeline.transform(req);

        assertFeatureVectorMatches(vector, want.get("feature_vector"), tolerance, raw);

        float[] rawProbs = runOnnx(env, session, vector);
        assertProbVectorMatches(
            rawProbs, want.get("raw_probabilities"), tolerance, "raw_probabilities", raw);

        double[] asDouble = new double[rawProbs.length];
        for (int c = 0; c < rawProbs.length; c++) asDouble[c] = rawProbs[c];
        double[] calibrated = calibrator.transform(new double[][] {asDouble})[0];
        assertProbVectorMatchesDouble(
            calibrated,
            want.get("calibrated_probabilities"),
            tolerance,
            "calibrated_probabilities",
            raw);
      }
    }
  }

  private static FeaturePipelinePitchPre.Request parseRequest(JsonNode raw) {
    return new FeaturePipelinePitchPre.Request(
        raw.get("count_balls").asInt(),
        raw.get("count_strikes").asInt(),
        raw.get("outs").asInt(),
        raw.get("inning").asInt(),
        raw.get("base_state").asInt(),
        raw.get("score_diff").asInt(),
        raw.get("dow").asInt(),
        raw.get("pitcher_throws").asText("R"),
        raw.get("batter_stand").asText("R"),
        raw.get("park_id").asText(""),
        raw.get("pitcher_id").asLong(),
        raw.get("batter_id").asLong(),
        nullableDouble(raw, "pitcher_pitches_last_28d"),
        nullableDouble(raw, "pitcher_pitches_in_game"),
        nullableDouble(raw, "days_since_last_appearance"),
        nullableDouble(raw, "pitcher_strike_rate_28d"),
        nullableDouble(raw, "pitcher_swstrike_rate_28d"),
        nullableDouble(raw, "pitcher_inplay_rate_28d"),
        nullableDouble(raw, "pitcher_strike_rate_std"),
        nullableDouble(raw, "batter_strike_rate_28d"),
        nullableDouble(raw, "batter_inplay_rate_28d"),
        nullableDouble(raw, "batter_ball_rate_28d"),
        nullableDouble(raw, "batter_inplay_rate_std"));
  }

  private static Double nullableDouble(JsonNode row, String key) {
    JsonNode v = row.get(key);
    if (v == null || v.isNull()) return null;
    return v.asDouble();
  }

  private static float[] runOnnx(OrtEnvironment env, OrtSession session, float[] vector)
      throws Exception {
    try (OnnxTensor tensor = OnnxTensor.createTensor(env, new float[][] {vector});
        OrtSession.Result result = session.run(Map.of("input", tensor))) {
      int size = result.size();
      Object probObj = (size == 1 ? result.get(0) : result.get(1)).getValue();
      float[][] probs = (float[][]) probObj;
      return probs[0];
    }
  }

  private static void assertFeatureVectorMatches(
      float[] actual, JsonNode expected, double tolerance, JsonNode raw) {
    assertNotNull(expected, "expected feature_vector is null");
    assertEquals(
        expected.size(),
        actual.length,
        "feature vector length mismatch on game_id=" + raw.get("game_id").asLong());
    for (int i = 0; i < actual.length; i++) {
      JsonNode wantNode = expected.get(i);
      double got = actual[i];
      // `null` on the wire ↔ NaN in memory (Tier 3 missing values)
      if (wantNode.isNull()) {
        assertTrue(
            Double.isNaN(got),
            String.format(
                "feature[%d] expected NaN but got %f on game_id=%d",
                i, got, raw.get("game_id").asLong()));
        continue;
      }
      double want = wantNode.asDouble();
      double drift = Math.abs(got - want);
      assertTrue(
          drift < tolerance,
          String.format(
              "feature[%d] drift > %g on game_id=%d: got %f wanted %f",
              i, tolerance, raw.get("game_id").asLong(), got, want));
    }
  }

  private static void assertProbVectorMatches(
      float[] actual, JsonNode expected, double tolerance, String stage, JsonNode raw) {
    assertEquals(
        expected.size(),
        actual.length,
        stage + " length mismatch on game_id=" + raw.get("game_id").asLong());
    for (int i = 0; i < actual.length; i++) {
      double drift = Math.abs(actual[i] - expected.get(i).asDouble());
      assertTrue(
          drift < tolerance,
          String.format(
              "%s[%d] drift > %g on game_id=%d: got %f wanted %f",
              stage,
              i,
              tolerance,
              raw.get("game_id").asLong(),
              actual[i],
              expected.get(i).asDouble()));
    }
  }

  private static void assertProbVectorMatchesDouble(
      double[] actual, JsonNode expected, double tolerance, String stage, JsonNode raw) {
    assertEquals(
        expected.size(),
        actual.length,
        stage + " length mismatch on game_id=" + raw.get("game_id").asLong());
    for (int i = 0; i < actual.length; i++) {
      double drift = Math.abs(actual[i] - expected.get(i).asDouble());
      assertTrue(
          drift < tolerance,
          String.format(
              "%s[%d] drift > %g on game_id=%d: got %f wanted %f",
              stage,
              i,
              tolerance,
              raw.get("game_id").asLong(),
              actual[i],
              expected.get(i).asDouble()));
    }
  }
}
